badge_lights_button:

  default:
    - entity: sensor.number_of_lights_on
    - name: Lights
    - icon: mdi:lightbulb
    - background_color: var(--button-card-on-background)
    - text_color: var(--button-card-on-text-color)
    - svg_path: 'M12,2A7,7 0 0,0 5,9C5,11.38 6.19,13.47 8,14.74V17A1,1 0 0,0 9,18H15A1,1 0 0,0 16,17V14.74C17.81,13.47 19,11.38 19,9A7,7 0 0,0 12,2M9,21A1,1 0 0,0 10,22H14A1,1 0 0,0 15,21V20H9V21Z'
    - svg_path_on: 'M 12,2 C 8.1340068,2 5,5.1340068 5,9 c 0,2.38 1.19,4.47 3,5.74 V 17 c 0,0.552285 0.4477153,1 1,1 h 6 c 0.552285,0 1,-0.447715 1,-1 V 14.74 C 17.81,13.47 19,11.38 19,9 19,5.1340068 15.865993,2 12,2'
    - cust_1_text_color: var(--button-card-cust-1-on-text-color)


  card:
    type: custom:decluttering-card
    template: badge_button_svg
    variables:
      - entity: '[[entity]]'
      - name: '[[name]]'
      - icon: '[[icon]]'
      - svg_fill: '[[svg_fill]]'
      - svg_path: '[[svg_path]]'
      - svg_fill_on: '[[svg_fill_on]]'
      - svg_path_on: '[[svg_path_on]]'
      - color: '[[color]]'
      - color_type: '[[color_type]]'
      - background_color: '[[background_color]]'
      - text_color: '[[text_color]]'
      - text_transform: none
      - cust_1_text_color: "[[cust_1_text_color]]"
      - cust_1_icon_color: "[[cust_1_icon_color]]"
      - cust_1_field: "[[[
            if ( entity.state == '0' )
              return 'Off';
            else if ( entity.state == '1' )
              return states['sensor.only_light_on'].state + ' On';
            else
              return entity.state + ' Lights On'; 
          ]]]"
      - state: "[[state]]"
      - hold_action:
          action: more-info
      - tap_action: 
          action: navigate
          navigation_path: /lovelace/lights/
      # - tap_action:
      #     #haptic: heavy
      #     action: fire-dom-event
      #     browser_mod:
      #       command: popup
      #       hide_header: false
      #       title: '[[name]]'
      #       large: true
            
      #       card:
       
      #         type: custom:layout-card
      #         layout_type: grid
      #         layout_options:
      #           grid-template-columns: 1fr
      #           grid-template-rows: auto
      #           mediaquery:
      #             "(min-width: 800px)":
      #               grid-template-columns: 700px
      #         cards:

      #           - type: custom:decluttering-card # Separator
      #             template: separator

      #           - !include /config/lovelace/cards/lights/card_lights_living_room_lightsview.yaml

      #           - !include /config/lovelace/cards/lights/card_lights_kitchen_lightsview.yaml

      #           - !include /config/lovelace/cards/lights/card_lights_bedroom_lightsview.yaml

      #           - !include /config/lovelace/cards/lights/card_lights_work_room_lightsview.yaml

      #           - !include /config/lovelace/cards/lights/card_lights_kids_room_lightsview.yaml

      #           - !include /config/lovelace/cards/lights/card_lights_hallway_lightsview.yaml

      #           #- !include /config/lovelace/cards/lights/card_lights_other_rooms.yaml

      #           #- !include /config/lovelace/cards/lights/card_lights_scripts.yaml


      #           - type: custom:decluttering-card # Separator
      #             template: separator
