badge_button_text:

  default:
    - cust_1_field: ""
    - cust_2_field: ""
    - corner_field: ""
    - corner_2_field: ""
    - color: auto
    - color_type: icon
    - box_shadow: var(--ha-card-box-shadow)
    - lock:
        enabled: false
        duration: 5
        unlock: tap
    - state:
        - value: "0"
          styles:
            card:
              #- background-color: var(--button-card-background-color)
              - color: var(--button-card-text-color) #'#040404'
            custom_fields:
              text_field:
                - --paper-item-icon-active-color: var(--paper-item-icon-color)
                - background-color: var(--button-card-background-color)
              cust_1:
                - color: var(--button-card-cust-1-text-color) #'#6F7075'
        - value: "unavailable"
          styles:
            icon:
              - color: var(--button-card-disabled-text-color)
            name:
              - color: var(--button-card-disabled-text-color)
            custom_fields:
              text_field:
                - --paper-item-icon-active-color: var(--button-card-disabled-text-color)
              cust_1:
                - color: var(--button-card-disabled-text-color)

    # Styles
    - border_radius: var(--button-card-border-radius)
    - background_color: var(--button-card-background-color)
    #- icon_color: var(--button-card-icon-color)
    - text_color: var(--button-card-text-color)
    - corner_text_color: var(--button-card-corner-text-color)
    - text_transform: capitalize
    - corner_2_text_color: var(--button-card-corner-text-color)
    - cust_1_text_color: var(--button-card-cust-1-text-color)
    - cust_2_text_color: var(--button-card-cust-2-text-color)
    - lock_color: var(--button-card-lock-color)
    - svg_fill: var(--button-card-svg-off-color)
    - svg_fill_on: var(--button-card-light-color-no-temperature)
    - text_field_color: var(--button-card-text-color)
    - border_color: var(--button-card-on-background)


  card:
    type: custom:button-card
    style: |
      ha-card {
        background: none;
        box-shadow: none;
      }
    entity: '[[entity]]'
    icon: '[[icon]]'
    aspect_ratio: 4/6
    #name: '[[name]]'
    show_name: false
    show_icon: false
    color: '[[color]]'
    color_type: '[[color_type]]'
    show_last_changed: false
    lock: '[[lock]]'
    styles:
      card:
        - padding: 8%
        - font-size: 12px
        - font-weight: bold
        - text-transform: '[[text_transform]]'
        - border-radius: '[[border_radius]]'
        #- background-color: rgba(0,0,0,0)
        - color: '[[text_color]]'
        - box-shadow: none;
        #- backdrop-filter: blur(20px)
      grid:
        - grid-template-areas: '"text_field" "cust_1"'
        - grid-template-rows: 4fr 2fr
      custom_fields:
        text_field:
          - display: flex
          - justify-content: center
          - align-items: center
          - font-size: 27px
          - font-weight: bold
          - text-align: center
          - line-height: 100%
          - align-self: center
          - justify-self: center
          - margin: none
          - height: 50%
          - width: 50%
          - padding-bottom: 22.4%
          - padding-top: 22.4%
          - padding-left: 24%
          - padding-right: 24%
          - background-color: '[[background_color]]'
          - color: '[[text_field_color]]'
          - border-radius: 50%
          - aspect_ratio: 1/1
          - box-shadow: '[[box_shadow]]'
          - border-color: '[[border_color]]'
          - border-style: solid
          - border-width: 3px
        cust_1:
          - line-height: 15px
          - height: 29px
          - overflow: hidden

          - text-overflow: ellipsis
          - display: -webkit-box
          - -webkit-box-orient: vertical
          - -webkit-line-clamp: 2

          #- display: flex
          - justify-content: center
          - align-items: self-start
          - align-self: normal
          - place-self: normal
          - padding-top: 4px
          - padding-bottom: 2px
          - align-self: center
          - justify-self: center
          - color: "[[cust_1_text_color]]"
          - --icon-color-sensor: "[[cust_1_icon_color]]"
          #- text-overflow: unset
          - white-space: unset
          - word-break: break-word
    custom_fields:  
      text_field: "[[text_field]]"
      cust_1: "[[cust_1_field]]"
    tap_action: '[[tap_action]]'
    hold_action: '[[hold_action]]'
    double_tap_action: '[[double_tap_action]]'
    state: "[[state]]"