button:

  default:
    - cust_1_field: ""
    - cust_2_field: ""
    - corner_field: ""
    - corner_2_field: ""
    - color: auto
    - color_type: icon
    - lock:
        enabled: false
        duration: 5
        unlock: tap
    - state:
        - value: "on"
          styles:
            card:
              - background-color: var(--button-card-on-background)
        - value: "unavailable"
          styles:
            icon:
              - color: var(--button-card-disabled-text-color)
            name:
              - color: var(--button-card-disabled-text-color)
            custom_fields:
              corner:
                - color: var(--button-card-disabled-text-color)
              corner_2:
                - color: var(--button-card-disabled-text-color)
              cust_1:
                - color: var(--button-card-disabled-text-color)
              cust_2:
                - color: var(--button-card-disabled-text-color)

    # Styles
    - border_radius: var(--button-card-border-radius)
    - background_color: var(--button-card-background-color)
    - icon_color: var(--button-card-icon-color)
    - text_color: var(--button-card-text-color)
    - corner_text_color: var(--button-card-corner-text-color)
    - corner_2_text_color: var(--button-card-corner-text-color)
    - cust_1_text_color: var(--button-card-cust-1-text-color)
    - cust_2_text_color: var(--button-card-cust-2-text-color)
    - lock_color: var(--button-card-lock-color)


  card:
    type: custom:button-card
    entity: '[[entity]]'
    icon: '[[icon]]'
    aspect_ratio: 1/1
    name: '[[name]]'
    color: '[[color]]'
    color_type: '[[color_type]]'
    show_last_changed: false
    lock: '[[lock]]'
    styles:
      card:
        - padding: 8%
        - font-size: 12px
        #- font-weight: bold
        - text-transform: lowercase
        - border-radius: '[[border_radius]]'
        - background-color: '[[background_color]]'
        - color: '[[text_color]]'
      grid:
        - grid-template-areas: '"i corner" "i corner_2" "n n" "cust_1 cust_1" "cust_2 cust_2"'
        - grid-template-columns: 1fr 1fr
        - grid-template-rows: 1fr 3fr 2fr 1fr 1fr
      name:
        - font-size: 16px
        - align-self: middle
        - justify-self: start
        - padding-top: 8px
        - padding-bottom: 4px
        - text-transform: lowercase        
      img_cell:
        - justify-content: start
        - align-items: start
        - margin: none
        - height: 100%
        - padding-bottom: 0px
        - color: '[[icon_color]]'
      icon:
        - width: 80%
        - height: 80%
        #- margin: none 
        - margin-top: 3% # Change to 5% for awesome
        - margin-left: 0% # Change to 5% for awesome
      lock:
        - color: '[[lock_color]]'
      custom_fields:
        corner:
          - align-self: start
          - justify-self: end
          - font-size: 14px
          - color: "[[corner_text_color]]"
          - --icon-color-sensor: "[[corner_icon_color]]"
        corner_2:
          - padding-top: 8px
          - align-self: start
          - justify-self: end
          - color: "[[corner_2_text_color]]"
          - --icon-color-sensor: "[[corner_2_icon_color]]"
        cust_1:
          - padding-bottom: 2px
          - align-self: middle
          - justify-self: start
          - color: "[[cust_1_text_color]]"
          - --icon-color-sensor: "[[cust_1_icon_color]]"
        cust_2:
          - padding-bottom: 2px
          - align-self: middle
          - justify-self: start
          - color: "[[cust_2_text_color]]"
          - --icon-color-sensor: "[[cust_2_icon_color]]"
    custom_fields:
      corner: "[[corner_field]]"
      corner_2: "[[corner_2_field]]"
      cust_1: "[[cust_1_field]]"
      cust_2: "[[cust_2_field]]"
    tap_action: '[[tap_action]]'
    hold_action: '[[hold_action]]'
    state: "[[state]]"