default:
  - border_radius: var(--graph-border-radius)
  - font_size: 70
  - font_size_header: 14
  - line_width: 5
  - show_icon: true
  - show_extrema: true
  - show_fill: true
  - icon: ""
  - color: ""

card:
  type: custom:mini-graph-card
  style: |
    ha-card {
      border-radius: [[border_radius]];
      overflow: hidden;
    }
  entities:
      - entity: '[[entity]]'
        name: '[[name]]'
        color: '[[color]]'
  icon: '[[icon]]'
  font_size: '[[font_size]]'
  font_size_header: '[[font_size_header]]'
  line_width: '[[line_width]]'
  show:
    icon: '[[show_icon]]'
    extrema: '[[show_extrema]]'
    fill: '[[show_fill]]'