motion_view_button:

  default:
    - entity: sensor.number_of_motion_sensors_on
    - name: Lights
    - icon: mdi:run
    - background_color: var(--button-card-on-background)
    - text_color: var(--button-card-on-text-color)
    - svg_path: 'M16.5,5.5A2,2 0 0,0 18.5,3.5A2,2 0 0,0 16.5,1.5A2,2 0 0,0 14.5,3.5A2,2 0 0,0 16.5,5.5M12.9,19.4L13.9,15L16,17V23H18V15.5L15.9,13.5L16.5,10.5C17.89,12.09 19.89,13 22,13V11C20.24,11.03 18.6,10.11 17.7,8.6L16.7,7C16.34,6.4 15.7,6 15,6C14.7,6 14.5,6.1 14.2,6.1L9,8.3V13H11V9.6L12.8,8.9L11.2,17L6.3,16L5.9,18L12.9,19.4M4,9A1,1 0 0,1 3,8A1,1 0 0,1 4,7H7V9H4M5,5A1,1 0 0,1 4,4A1,1 0 0,1 5,3H10V5H5M3,13A1,1 0 0,1 2,12A1,1 0 0,1 3,11H7V13H3Z'
    - svg_fill_on: var(--paper-item-icon-active-color)
    - svg_path_on: 'm 16.5,5.5 c 1.104569,0 2,-0.8954305 2,-2 0,-1.1045695 -0.895431,-2 -2,-2 -1.104569,0 -2,0.8954305 -2,2 0,1.1045695 0.895431,2 2,2 m -3.6,13.9 1,-4.4 2.1,2 v 6 h 2 v -7.5 l -2.1,-2 0.6,-3 C 17.89,12.09 19.89,13 22,13 V 11 C 20.24,11.03 18.6,10.11 17.7,8.6 L 16.7,7 C 16.34,6.4 15.7,6 15,6 14.7,6 14.5,6.1 14.2,6.1 L 9,8.3 V 13 h 2 V 9.6 l 1.8,-0.7 -1.6,8.1 -4.9,-1 -0.4,2 7,1.4'
    - cust_2_field: ""
    - cust_1_text_color: var(--button-card-cust-1-on-text-color)
    - cust_2_text_color: var(--button-card-cust-2-on-text-color)
    - corner_border_radius: 12px
    - corner_text_color: "var(--button-card-text-field-color)"
    - corner_background_color: rgba(0,0,0,0)
    - corner_field: ''
    - state:
        - value: "0"
          styles:
            card:
              - background-color: var(--button-card-background-color)
              - color: var(--button-card-text-color) #'#040404'
            custom_fields:
              svg_icon:
                - --paper-item-icon-active-color: var(--paper-item-icon-color)
              #corner:
              #  - color: var(--button-card-corner-on-text-color) #'#6F7075'
              #corner_2:
              #  - color: var(--button-card-corner-on-text-color) #'#6F7075'
              cust_1:
                - color: var(--button-card-cust-1-text-color) #'#6F7075'
              cust_2:
                - color: var(--button-card-cust-2-text-color) #'#6F7075'
        - value: "unavailable"
          styles:
            icon:
              - color: var(--button-card-disabled-text-color)
            name:
              - color: var(--button-card-disabled-text-color)
            custom_fields:
              svg_icon:
                - --paper-item-icon-active-color: var(--button-card-disabled-text-color)
              corner:
                - color: var(--button-card-disabled-text-color)
              corner_2:
                - color: var(--button-card-disabled-text-color)
              cust_1:
                - color: var(--button-card-disabled-text-color)
              cust_2:
                - color: var(--button-card-disabled-text-color)


  card:
    type: custom:decluttering-card
    template: button_two_rows_svg
    variables:
      - entity: '[[entity]]'
      - name: '[[name]]'
      - icon: '[[icon]]'
      - svg_fill: '[[svg_fill]]'
      - svg_path: '[[svg_path]]'
      - svg_fill_on: '[[svg_fill_on]]'
      - svg_path_on: '[[svg_path_on]]'
      - color: '[[color]]'
      - color_type: '[[color_type]]'
      - background_color: '[[background_color]]'
      - text_color: '[[text_color]]'
      - text_transform: none
      - corner_text_color: "[[corner_text_color]]"
      - corner_icon_color: ""
      - cust_1_text_color: "[[cust_1_text_color]]"
      - cust_1_icon_color: "[[cust_1_icon_color]]"
      - cust_2_text_color: "[[cust_2_text_color]]"
      - cust_2_icon_color: "[[cust_2_icon_color]]"
      # - corner_field: "[[[ 
      #       if ( entity.state == '0' )
      #         return '';
      #       else
      #         return entity.state; 
      #     ]]]"
      - corner_field: "[[corner_field]]"
      - corner_border_radius: "[[corner_border_radius]]"
      # - corner_background_color: "[[[
      #       if ( entity.state == '0' )
      #         return 'rgba(0,0,0,0)';
      #       else
      #         return 'var(--secondary-text-color)';
      #     ]]]"
      - corner_background_color: "[[corner_background_color]]"
      - cust_1_field: "[[[
            if ( entity.state == '0' )
              return 'Clear';
            else if ( entity.state == '1' )
              return states['sensor.only_motion_sensor_on'].state;
            else
              return 'In ' + entity.state + ' Rooms'; 
          ]]]"

      - cust_2_field: "[[cust_2_field]]"
      - state: "[[state]]"
      - hold_action:
          action: more-info
      - tap_action:
          #haptic: heavy
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: false
            title: '[[name]]'
            large: false
            
            card:

              type: vertical-stack
              cards:

                - !include /config/lovelace/styles/separator_card.yaml
        
                - type: horizontal-stack
                  cards:

                    - type: custom:button-card
                      template: shoulder_blank_card
                        
                    - type: custom:layout-card
                      min_columns: 1
                      max_columns: 3
                      cards:

                        - !include /config/lovelace/cards/xiaomi/card_motion_sensors.yaml

                    - type: custom:button-card
                      template: shoulder_blank_card

                - !include /config/lovelace/styles/separator_card.yaml
