rooms_menu:

  default:
    - color: auto
    - color_type: icon
    - border_radius: var(--button-card-border-radius)
    - background_color: var(--button-card-background-color)
    - text_color: var(--button-card-text-color)
    - text_transform: capitalize
    - svg_fill: var(--button-card-svg-off-color)
    - svg_fill_on: var(--paper-item-icon-color)
    - entity: ""
    - temp_entity: ""
    - motion_entity: ""
    - light_entity: ""
    - svg_fill_disabled: var(--button-card-disabled-text-color)
    - light_svg_fill: var(--button-card-svg-off-color)
    - light_svg_fill_on: var(--paper-item-icon-active-color)
    - light_svg_fill_off: var(--paper-item-icon-color)
    # - light_svg_path: 'M12,2A7,7 0 0,0 5,9C5,11.38 6.19,13.47 8,14.74V17A1,1 0 0,0 9,18H15A1,1 0 0,0 16,17V14.74C17.81,13.47 19,11.38 19,9A7,7 0 0,0 12,2M9,21A1,1 0 0,0 10,22H14A1,1 0 0,0 15,21V20H9V21Z'
    # - light_svg_path_colored: 'M 12,2 C 8.1340068,2 5,5.1340068 5,9 c 0,2.38 1.19,4.47 3,5.74 V 17 c 0,0.552285 0.4477153,1 1,1 h 6 c 0.552285,0 1,-0.447715 1,-1 V 14.74 C 17.81,13.47 19,11.38 19,9 19,5.1340068 15.865993,2 12,2'
    # - light_svg_path_on: 'M12,2A7,7 0 0,0 5,9C5,11.38 6.19,13.47 8,14.74V17A1,1 0 0,0 9,18H15A1,1 0 0,0 16,17V14.74C17.81,13.47 19,11.38 19,9A7,7 0 0,0 12,2M9,21A1,1 0 0,0 10,22H14A1,1 0 0,0 15,21V20H9V21Z'    
    # - light_svg_path_colored_on: 'M 12,2 C 8.1340068,2 5,5.1340068 5,9 c 0,2.38 1.19,4.47 3,5.74 V 17 c 0,0.552285 0.4477153,1 1,1 h 6 c 0.552285,0 1,-0.447715 1,-1 V 14.74 C 17.81,13.47 19,11.38 19,9 19,5.1340068 15.865993,2 12,2'
    - light_svg_path: 'M272 384.008V416.008L272 416.008L271.938 454.329C271.938 459.657 269.531 467.594 266.594 472.032L249.5 497.719C244.25 505.594 232.312 512 222.875 512H161.156C151.688 512 139.75 505.594 134.5 497.719L117.406 472.032C113.938 466.782 112.062 460.625 112.062 454.329L112 416.008L112 416.008V384.008H272Z'
    - light_svg_path_colored: 'M191.438 0C89.438 0.313 16 82.969 16 175.993C16 220.368 32.438 260.836 59.562 291.774C76.094 310.618 101.906 350.004 111.781 383.223C111.812 383.473 111.844 383.739 111.875 384.004H272.125C272.156 383.739 272.187 383.489 272.219 383.223C282.094 350.004 307.906 310.618 324.437 291.774C351.562 260.836 368 220.368 368 175.993C368 78.61 288.906 -0.296 191.438 0ZM192 95.997C147.875 95.997 112 131.887 112 175.993C112 184.836 104.844 191.993 96 191.993S80 184.836 80 175.993C80 114.231 130.25 64 192 64C200.844 64 208 71.157 208 80S200.844 95.997 192 95.997Z'
    - light_svg_path_on: 'M272 384.008V416.008L272 416.008L271.938 454.329C271.938 459.657 269.531 467.594 266.594 472.032L249.5 497.719C244.25 505.594 232.312 512 222.875 512H161.156C151.688 512 139.75 505.594 134.5 497.719L117.406 472.032C113.938 466.782 112.062 460.625 112.062 454.329L112 416.008L112 416.008V384.008H272Z'
    - light_svg_path_colored_on: 'M191.438 0C89.438 0.313 16 82.969 16 175.993C16 220.368 32.438 260.836 59.562 291.774C76.094 310.618 101.906 350.004 111.781 383.223C111.812 383.473 111.844 383.739 111.875 384.004H272.125C272.156 383.739 272.187 383.489 272.219 383.223C282.094 350.004 307.906 310.618 324.437 291.774C351.562 260.836 368 220.368 368 175.993C368 78.61 288.906 -0.296 191.438 0ZM192 95.997C147.875 95.997 112 131.887 112 175.993C112 184.836 104.844 191.993 96 191.993S80 184.836 80 175.993C80 114.231 130.25 64 192 64C200.844 64 208 71.157 208 80S200.844 95.997 192 95.997Z'    
    - motion_svg_fill: var(--button-card-svg-off-color)
    - motion_svg_fill_on: var(--paper-item-icon-active-color)
    - motion_svg_fill_off: var(--paper-item-icon-color)
    # - motion_svg_path: 'M13.5,5.5C14.59,5.5 15.5,4.58 15.5,3.5C15.5,2.38 14.59,1.5 13.5,1.5C12.39,1.5 11.5,2.38 11.5,3.5C11.5,4.58 12.39,5.5 13.5,5.5M9.89,19.38L10.89,15L13,17V23H15V15.5L12.89,13.5L13.5,10.5C14.79,12 16.79,13 19,13V11C17.09,11 15.5,10 14.69,8.58L13.69,7C13.29,6.38 12.69,6 12,6C11.69,6 11.5,6.08 11.19,6.08L6,8.28V13H8V9.58L9.79,8.88L8.19,17L3.29,16L2.89,18L9.89,19.38Z'
    # - motion_svg_path_colored: 'M13.5,5.5C14.59,5.5 15.5,4.58 15.5,3.5C15.5,2.38 14.59,1.5 13.5,1.5C12.39,1.5 11.5,2.38 11.5,3.5C11.5,4.58 12.39,5.5 13.5,5.5M9.89,19.38L10.89,15L13,17V23H15V15.5L12.89,13.5L13.5,10.5C14.79,12 16.79,13 19,13V11C17.09,11 15.5,10 14.69,8.58L13.69,7C13.29,6.38 12.69,6 12,6C11.69,6 11.5,6.08 11.19,6.08L6,8.28V13H8V9.58L9.79,8.88L8.19,17L3.29,16L2.89,18L9.89,19.38Z'
    # - motion_svg_path_on: 'M16.5,5.5A2,2 0 0,0 18.5,3.5A2,2 0 0,0 16.5,1.5A2,2 0 0,0 14.5,3.5A2,2 0 0,0 16.5,5.5M12.9,19.4L13.9,15L16,17V23H18V15.5L15.9,13.5L16.5,10.5C17.89,12.09 19.89,13 22,13V11C20.24,11.03 18.6,10.11 17.7,8.6L16.7,7C16.34,6.4 15.7,6 15,6C14.7,6 14.5,6.1 14.2,6.1L9,8.3V13H11V9.6L12.8,8.9L11.2,17L6.3,16L5.9,18L12.9,19.4M4,9A1,1 0 0,1 3,8A1,1 0 0,1 4,7H7V9H4M5,5A1,1 0 0,1 4,4A1,1 0 0,1 5,3H10V5H5M3,13A1,1 0 0,1 2,12A1,1 0 0,1 3,11H7V13H3Z'
    # - motion_svg_path_colored_on: 'm 16.5,5.5 c 1.104569,0 2,-0.8954305 2,-2 0,-1.1045695 -0.895431,-2 -2,-2 -1.104569,0 -2,0.8954305 -2,2 0,1.1045695 0.895431,2 2,2 m -3.6,13.9 1,-4.4 2.1,2 v 6 h 2 v -7.5 l -2.1,-2 0.6,-3 C 17.89,12.09 19.89,13 22,13 V 11 C 20.24,11.03 18.6,10.11 17.7,8.6 L 16.7,7 C 16.34,6.4 15.7,6 15,6 14.7,6 14.5,6.1 14.2,6.1 L 9,8.3 V 13 h 2 V 9.6 l 1.8,-0.7 -1.6,8.1 -4.9,-1 -0.4,2 7,1.4'
    - motion_svg_path: 'M384 32H64C28.625 32 0 60.625 0 96V416C0 451.375 28.625 480 64 480H384C419.375 480 448 451.375 448 416V96C448 60.625 419.375 32 384 32ZM96 272C96 280.875 88.875 288 80 288S64 280.875 64 272V112C64 103.125 71.125 96 80 96S96 103.125 96 112V272ZM160 272C160 280.875 152.875 288 144 288S128 280.875 128 272V112C128 103.125 135.125 96 144 96S160 103.125 160 112V272ZM224 272C224 280.875 216.875 288 208 288S192 280.875 192 272V112C192 103.125 199.125 96 208 96S224 103.125 224 112V272Z'
    - motion_svg_path_on: 'M384 32H64C28.625 32 0 60.625 0 96V416C0 451.375 28.625 480 64 480H384C419.375 480 448 451.375 448 416V96C448 60.625 419.375 32 384 32ZM96 272C96 280.875 88.875 288 80 288S64 280.875 64 272V112C64 103.125 71.125 96 80 96S96 103.125 96 112V272ZM160 272C160 280.875 152.875 288 144 288S128 280.875 128 272V112C128 103.125 135.125 96 144 96S160 103.125 160 112V272ZM224 272C224 280.875 216.875 288 208 288S192 280.875 192 272V112C192 103.125 199.125 96 208 96S224 103.125 224 112V272Z'
    - motion_svg_path_colored: 'm 208,96 c -8.875,0 -16,7.125 -16,16 v 160 c 0,8.875 7.125,16 16,16 8.875,0 16,-7.125 16,-16 V 112 c 0,-8.875 -7.125,-16 -16,-16 z m -64,0 c -8.875,0 -16,7.125 -16,16 v 160 c 0,8.875 7.125,16 16,16 8.875,0 16,-7.125 16,-16 V 112 c 0,-8.875 -7.125,-16 -16,-16 z m -64,0 c -8.875,0 -16,7.125 -16,16 v 160 c 0,8.875 7.125,16 16,16 8.875,0 16,-7.125 16,-16 V 112 C 96,103.125 88.875,96 80,96 Z'
    - motion_svg_path_colored_on: 'M208 96C199.125 96 192 103.125 192 112V272C192 280.875 199.125 288 208 288S224 280.875 224 272V112C224 103.125 216.875 96 208 96ZM144 96C135.125 96 128 103.125 128 112V272C128 280.875 135.125 288 144 288S160 280.875 160 272V112C160 103.125 152.875 96 144 96ZM80 96C71.125 96 64 103.125 64 112V272C64 280.875 71.125 288 80 288S96 280.875 96 272V112C96 103.125 88.875 96 80 96ZM616 232H552C538.75 232 528 242.75 528 256S538.75 280 552 280H616C629.25 280 640 269.25 640 256S629.25 232 616 232ZM597.25 404L549.25 372C538.25 364.625 523.375 367.625 516 378.75C508.625 389.75 511.625 404.625 522.75 412L570.75 444C581.75 451.375 596.625 448.375 604 437.25C611.375 426.25 608.375 411.375 597.25 404ZM536 144C540.75 144 545.375 142.625 549.25 140L597.25 108C604.625 103.375 609 95.125 608.5 86.375S602.875 69.875 595 66C587.125 62.25 577.75 63 570.625 68.125L522.625 100.125C513.875 106 510 116.875 513.125 127C516.125 137.125 525.5 144 536 144Z'    
    - temp_field_color: var(--button-card-cust-1-text-color)
    - svg_icon_x: 0
    - svg_icon_y: 0
    - svg_icon_width: 24
    - svg_icon_height: 24


  card:
    type: custom:button-card
    entity: '[[entity]]'
    #icon: '[[icon]]'
    name: '[[name]]'
    #color: '[[color]]'
    #color_type: '[[color_type]]'
    show_last_changed: false
    styles:
      card:
        - padding: 10%
        - font-size: 12px
        - font-weight: bold
        - text-transform: '[[text_transform]]'
        - border-radius: '[[border_radius]]'
        - background-color: '[[background_color]]'
        - color: '[[text_color]]'
        - backdrop-filter: blur(20px)
        - padding: 10px
      grid:
        - grid-template-areas: '"svg_icon n temp motion light"'
        #- grid-template-columns: 2fr 4.5fr 1.5fr 1fr 1fr
        - grid-template-columns: "[[[
            if ( '[[motion_entity]]' == '' )
              return '2fr 5.5fr 1.5fr 0fr 1fr';
            else
              return '2fr 4.5fr 1.5fr 1fr 1fr';
            ]]]"
        - grid-template-rows: 1fr
      name:
        - font-size: 1.50em
        - align-self: middle
        - justify-self: start
        - align-self: center
        - padding-top: 0px
        - padding-bottom: 0px
        - padding-left: 10px
        #- text-transform: lowercase
      custom_fields:
        svg_icon:
          - align-self: center
          - justify-self: center
          - margin: none
          - height: 60%
          - width: 60%
          - padding-bottom: 10px
          - padding-top: 0px
          #- color: '[[icon_color]]'
        temp:
          - font-size: 1.30em
          - color: '[[temp_field_color]]'
        motion:
          - align-self: center
          - justify-self: center
          - margin: none
          - height: 80%
          - width: 78%
          - padding-bottom: 0px
          - padding-top: 18px
        light:
          - align-self: center
          - justify-self: center
          - margin: none
          - height: 80%
          - width: 80%
          - padding-bottom: 0px
          - padding-top: 18px
    custom_fields:  
      svg_icon: "[[[ 
        return `<svg viewBox='[[svg_icon_x]] [[svg_icon_y]] [[svg_icon_width]] [[svg_icon_height]]'>
        <path fill='[[svg_fill]]' d='[[svg_path]]'/>
        <path fill='[[svg_fill_on]]' d='[[svg_path_colored]]'/> </svg>`;
        ]]]"
      temp: "[[[ 
        if ( '[[temp_entity]]' == '' )
          return '';
        else
          return states['[[temp_entity]]'].state + 'Â°';
        ]]]"
      motion: "[[[ 
        if ( '[[motion_entity]]' == '' )
          return '';
        else if ( states['[[motion_entity]]'].state === 'on' )
          return `<svg viewBox='0 -64 640 640'>
          <path fill='[[motion_svg_fill]]' d='[[motion_svg_path_on]]'/>
          <path fill='[[motion_svg_fill_on]]' d='[[motion_svg_path_colored_on]]'/> </svg>`;
        else
          return `<svg viewBox='0 -64 640 640'>
          <path fill='[[motion_svg_fill]]' d='[[motion_svg_path]]'/>
          <path fill='[[motion_svg_fill_off]]' d='[[motion_svg_path_colored]]'/> </svg>`;
        ]]]"
      light: "[[[ 
        if ( '[[light_entity]]' == '' )
          return `<svg viewBox='-64 0 512 512'>
          <path fill='[[svg_fill_disabled]]' d='[[light_svg_path]]'/> </svg>`;
        else if ( states['[[light_entity]]'].state === 'on' )
          return `<svg viewBox='-64 0 512 512'>
          <path fill='[[light_svg_fill]]' d='[[light_svg_path_on]]'/>
          <path fill='[[light_svg_fill_on]]' d='[[light_svg_path_colored_on]]'/> </svg>`;
        else
          return `<svg viewBox='-64 0 512 512'>
          <path fill='[[light_svg_fill]]' d='[[light_svg_path]]'/>
          <path fill='[[light_svg_fill_off]]' d='[[light_svg_path_colored]]'/> </svg>`;
        ]]]"
    tap_action: 
      action: navigate
      navigation_path: /lovelace/[[path]]/
    hold_action: '[[hold_action]]'
    double_tap_action: '[[double_tap_action]]'
    #state: "[[state]]"