school_button:

  default:
    - icon: mdi:school
    - cust_2_field: ""
    - svg_fill_on: '#bf4040'
    # - svg_path: 'M12,3L1,9L12,15L21,10.09V17H23V9M5,13.18V17.18L12,21L19,17.18V13.18L12,17L5,13.18Z'
    # - svg_path_on: 'M12,3L1,9L12,15L21,10.09V17H23V9M5,13.18V17.18L12,21L19,17.18V13.18L12,17L5,13.18Z'
    # - svg_path_colored: 'm 5,13.18 v 4 l 7,3.82 7,-3.82 v -4 L 12,17 Z'
    # - svg_path_colored_on: 'm 5,13.18 v 4 l 7,3.82 7,-3.82 v -4 L 12,17 Z'
    - svg_path: 'M323.991 143.516L161.116 184.234C121.749 194.09 92.515 225.01 83.393 263.113L83.393 263.113C90.942 268.969 96.116 277.707 96.116 288C96.116 297.953 91.302 306.488 84.177 312.359L109.011 461.367C110.636 471.121 103.116 480 93.229 480H35.003C25.116 480 17.597 471.121 19.222 461.367L44.056 312.359C36.931 306.488 32.116 297.953 32.116 288C32.116 274.758 40.163 263.395 51.634 258.531L51.634 258.531C62.657 207.693 101.216 166.248 153.366 153.203L316.241 112.484C324.679 110.234 333.522 115.531 335.647 124.125C337.772 132.688 332.585 141.375 323.991 143.516Z'
    - svg_path_on: 'M323.991 143.516L161.116 184.234C121.749 194.09 92.515 225.01 83.393 263.113L83.393 263.113C90.942 268.969 96.116 277.707 96.116 288C96.116 297.953 91.302 306.488 84.177 312.359L109.011 461.367C110.636 471.121 103.116 480 93.229 480H35.003C25.116 480 17.597 471.121 19.222 461.367L44.056 312.359C36.931 306.488 32.116 297.953 32.116 288C32.116 274.758 40.163 263.395 51.634 258.531L51.634 258.531C62.657 207.693 101.216 166.248 153.366 153.203L316.241 112.484C324.679 110.234 333.522 115.531 335.647 124.125C337.772 132.688 332.585 141.375 323.991 143.516Z'
    - svg_path_colored: 'M640 160C640 170.383 633.562 179.648 623.953 183.086L341.215 284.316C327.482 289.227 312.518 289.227 298.785 284.316L108.234 216.092C121.963 200.908 139.961 189.502 161 184.234L323.875 143.516C332.469 141.375 337.656 132.688 335.531 124.125C333.406 115.531 324.563 110.234 316.125 112.484L153.25 153.203C121.406 161.168 94.732 179.807 76.199 204.623L16.047 183.086C6.438 179.648 0 170.383 0 160S6.438 140.352 16.047 136.914L298.785 35.684C312.518 30.773 327.482 30.773 341.215 35.684L623.953 136.914C633.562 140.352 640 149.617 640 160ZM351.988 314.449C341.688 318.133 330.926 320 320 320C309.076 320 298.312 318.133 287.998 314.445L142.781 262.453L128 405.328C128 446.602 213.999 480 320 480C425.999 480 512 446.602 512 405.328L497.219 262.453L351.988 314.449Z'
    - svg_path_colored_on: 'M640 160C640 170.383 633.562 179.648 623.953 183.086L341.215 284.316C327.482 289.227 312.518 289.227 298.785 284.316L108.234 216.092C121.963 200.908 139.961 189.502 161 184.234L323.875 143.516C332.469 141.375 337.656 132.688 335.531 124.125C333.406 115.531 324.563 110.234 316.125 112.484L153.25 153.203C121.406 161.168 94.732 179.807 76.199 204.623L16.047 183.086C6.438 179.648 0 170.383 0 160S6.438 140.352 16.047 136.914L298.785 35.684C312.518 30.773 327.482 30.773 341.215 35.684L623.953 136.914C633.562 140.352 640 149.617 640 160ZM351.988 314.449C341.688 318.133 330.926 320 320 320C309.076 320 298.312 318.133 287.998 314.445L142.781 262.453L128 405.328C128 446.602 213.999 480 320 480C425.999 480 512 446.602 512 405.328L497.219 262.453L351.988 314.449Z'
    #- cust_1_field: "[[[ return states['sensor.school_summary'].state; ]]]"
    - entity: binary_sensor.school_holiday
    - name: "לימודים"



  card:
    type: custom:decluttering-card
    template: button_two_rows_svg
    variables:
      - entity: '[[entity]]'
      - name: '[[name]]'
      - icon: '[[icon]]'
      - svg_fill: '[[svg_fill]]'
      - svg_path: '[[svg_path]]'
      - svg_fill_on: '[[svg_fill_on]]'
      - svg_path_on: '[[svg_path_on]]'
      - svg_path_colored: '[[svg_path_colored]]'
      - svg_path_colored_on: '[[svg_path_colored_on]]'
      - svg_icon_y: -64
      - svg_icon_width: 640
      - svg_icon_height: 640
      - color: '[[color]]'
      - color_type: '[[color_type]]'
      - text_transform: none
      - corner_text_color: "[[corner_text_color]]"
      - corner_icon_color: ""
      - cust_1_text_color: "[[cust_1_text_color]]"
      - cust_1_icon_color: "[[cust_1_icon_color]]"
      - cust_2_text_color: "[[cust_2_text_color]]"
      - cust_2_icon_color: "[[cust_2_icon_color]]"
      - corner_field: "[[corner_field]]"
      - corner_border_radius: "[[corner_border_radius]]"
      - corner_background_color: "[[corner_background_color]]"
      - cust_1_field: "[[[
            if (entity.state == 'on')
              return states['sensor.school_summary'].state;
            else
              return 'יום לימודים'; 
          ]]]"
      - cust_2_field: "[[cust_2_field]]"
      - state: "[[state]]"
      - hold_action:
          action: more-info
      - tap_action:
          #haptic: heavy
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: true
            title: '[[name]]'
            
            card:

              type: custom:layout-card
              layout_type: vertical
              cards:

                - type: custom:decluttering-card
                  template: view_title_button
                  variables:
                    - padding_top: '2px'
                    - title: '[[name]]'
                    - back_button: true
                    - tap_action:
                        action: 'fire-dom-event'
                        browser_mod:
                          command: 'close_popup'              

                - type: entities
                  state_color: true
                  show_header_toggle: false
                  style: |
                    ha-card.type-entities {
                      background: none;
                      box-shadow: none;
                      padding: 0.3em 1.25em 0.4em 0.5em;
                    }
                  entities:

                    - entity: sensor.school_summary
                      name: Summary
                    - entity: sensor.school_is_elementary_vacation
                      name: Vacation
                    - entity: input_boolean.school_auto
                      name: School Mode    
                    
