sensibo_card:

  default:
    - cool_color: var(--sensibo-cool-color)
    - heat_color: var(--sensibo-heat-color)

  card:
    type: vertical-stack
    cards:


############################################################################
#                                                                          #
#   Title                                                                  #
#                                                                          #
############################################################################

      - type: horizontal-stack
        cards:
        
          - type: custom:button-card
            template: shoulder_blank_card  
          
          - type: custom:decluttering-card
            template: title_button_card
            variables:
              - name: '[[title]]'
          
          - type: custom:button-card
            template: shoulder_blank_card  

            
############################################################################
#                                                                          #
#   Picture with dynamic display                                           #
#                                                                          #
############################################################################

      - type: horizontal-stack
        cards:

          - type: custom:button-card
            template: shoulder_blank_card

          - type: custom:decluttering-card
            template: sensibo_elements
            variables:
              - image_off: '[[image_off]]'
              - image_on: '[[image_on]]'
              - entity: 'climate.[[name]]'
              - sensor_target_temp: 'sensor.sensibo_[[name]]_target_temp'
              - sensor_temp: 'sensor.sensibo_[[name]]_temp'
              - sensor_fan: 'sensor.sensibo_[[name]]_fan'
                
          - type: custom:button-card
            template: shoulder_blank_card      

############################################################################
#                                                                          #
#   On/Off and Operation set                                               #
#                                                                          #
############################################################################

      - type: horizontal-stack
        cards:
        
          - type: custom:button-card
            template: shoulder_blank_card

          - type: custom:decluttering-card # Cool Operation Mode
            template: simple_button
            variables:
              - entity: switch.sensibo_[[name]]_cool
              - name: Cool
              - icon: mdi:snowflake
              - state:
                  - value: "on"
                    styles:
                      card:
                        - background-color: '[[cool_color]]'

          - type: custom:decluttering-card # Heat Operation Mode
            template: simple_button
            variables:
              - entity: switch.sensibo_[[name]]_heat
              - name: Heat
              - icon: mdi:fire
              - state:
                  - value: "on"
                    styles:
                      card:
                        - background-color: '[[heat_color]]'

          - type: custom:decluttering-card # Decrease Target Temperature
            template: simple_script_button
            variables:
              - entity: script.sensibo_[[name]]_decrease_target_temp
              - icon: mdi:minus

          - type: custom:decluttering-card # Increase Target Temperature
            template: simple_script_button
            variables:
              - entity: script.sensibo_[[name]]_increase_target_temp
              - icon: mdi:plus

          - type: custom:button-card
            template: shoulder_blank_card

      - !include /config/lovelace/styles/separator_card.yaml