simple_button:

  default:
    - show_name: false
    - show_icon: true
    - border_radius: var(--button-card-border-radius)
    - background_color: var(--button-card-background-color)
    - name_color: var(--button-card-text-color)
    - icon_color: var(--button-card-icon-color)
    - size: 48px
    - width: ""
    - height: 54px
    - font_size: 14px
    - font_weight: normal
    - padding_top: 3%
    - padding_bottom: 3%
    - lock: false
    - lock_color: var(--button-card-lock-color)
    - tap_action:
        action: toggle
    - hold_action:
        action: none
    - state:
        - value: "on"
          styles:
            card:
              - background-color: 'var(--button-color-green)'
            icon:
              - color: 'var(--primary-text-color)'

  card:
    type: custom:button-card
    entity: '[[entity]]'
    name: '[[name]]'
    icon: '[[icon]]'
    color_type: card
    show_state: false
    show_label: false
    show_name: '[[show_name]]'
    show_icon: '[[show_icon]]'
    size: '[[size]]'
    layout: vertical
    lock: '[[lock]]'
    styles:
      card:
        - border-radius: '[[border_radius]]'
        - background-color: '[[background_color]]'
        - padding-top: '[[padding_top]]'
        - padding-bottom: '[[padding_bottom]]'
        - font-weight: '[[font_weight]]'
        - width: '[[width]]'
        - height: '[[height]]'
      name:
        - text-transform: lowercase
        - color: '[[name_color]]'
        - font-size: '[[font_size]]'
      img_cell:
        - color: '[[icon_color]]'
      lock:
        - color: '[[lock_color]]'
    state:
      '[[state]]'
    tap_action:
      '[[tap_action]]'
    hold_action:
      '[[hold_action]]'