widget_mini_graph_bar:
  variables:
    mini_graph_name: ''
    mini_graph_color: ''
    mini_graph_entity: ''
    mini_graph_attribute : ''
    mini_graph_max: 100
    mini_graph_min: 0
  show_icon: false
  show_name: false
  show_label: false
  styles:
    card:
      - border-radius: "20px"
      - background: "none"
      - box-shadow: "none"
      - padding: "0px"
    grid:
      - grid-template-areas: "'item1'"
      - grid-template-columns: "1fr"
      - grid-template-rows: "min-content"
  custom_fields:
    item1:
      card:
        type: "custom:bar-card"
        height: "20px"
        positions:
          name: "inside"
          value: "inside"
          icon: off
          indicator: off
          minmax: off
        max: '[[[ return variables.mini_graph_max ]]]'
        min: '[[[ return variables.mini_graph_min ]]]'
        name: '[[[ return variables.mini_graph_name ]]]'
        color: '[[[ return variables.mini_graph_color ]]]'
        entity: "[[[ return variables.mini_graph_entity ]]]"
        attribute: "[[[ return variables.mini_graph_attribute ]]]"
        style: |
          bar-card-currentbar{
            border: 0.01rem solid rgba(var(--color-theme),.4);
          }
          bar-card-backgroundbar{
            display: none;
          }
          bar-card-name{
            width: 8rem;
            margin-left: 10px !important;
            justify-content: start;
            display: flex;
            color: rgba(var(--primary-text-color),1);
            padding-top: 1px;
          }
          bar-card-value{
            width: 2rem;
            margin-left: 40px !important;
            justify-content: center;
            display: flex;
            color: rgba(var(--primary-text-color),1);
            padding-top: 1px;
          }
          bar-card-background{
            margin: 4px 0 4px 0 !important;
            text-align: initial;
          }
          ha-card{
            --bar-card-border-radius: 5px;
            border-radius: 0px;
            box-shadow: none;
            background: none;
          }
          #states{
            padding: 0 16px;
          }