title: System

# custom_header:
#   !include /config/lovelace/custom_header.yaml

# Button card templates  
decluttering_templates:
  !include_dir_merge_named /config/lovelace/decluttering_templates/

button_card_templates:
  !include_dir_merge_named /config/lovelace/button_card_templates/
   
background: var(--background-image)    
views:

    # Hassio Tab        
    - !include /config/lovelace/views/view_homeassistant.yaml
    # Automation
    - !include /config/lovelace/views/view_automation.yaml
    # Devices Tab
    - !include /config/lovelace/views/view_ha_devices.yaml
    # Wall Panel
    - !include /config/lovelace/views/view_wallpanel.yaml
    # Sysytem Tab        
    - !include /config/lovelace/views/view_system.yaml
    # Batteries
    - !include /config/lovelace/views/view_batteries.yaml