popup_school_day:
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        title: "[[[ return variables.ulm_school_day; ]]]"
        content:


          type: horizontal-stack
          cards:

            - type: custom:button-card
              template: card_blank

            - type: vertical-stack
              cards:

                ############################################################################
                #                                                                          #
                #   Header                                                                 #
                #                                                                          #
                ############################################################################

                - type: "custom:button-card"
                  template: 
                    - 'popup_header_ha_style'
                  triggers_update: all
                  entity: sensor.school_summary


                - type: "custom:button-card"
                  template: spacer
                  variables:
                    height: 20px

                ############################################################################
                #                                                                          #
                #   Sensors                                                                #
                #                                                                          #
                ############################################################################


                - type: grid
                  square: false
                  columns: 1
                  cards:

                    # Elementary School
                    - type: "custom:button-card"
                      template: 
                        - "popup_text_info"
                        - "direction_rtl"
                        - "popup_school_elementary_info"
                        - "ulm_language_variables"
                      custom_fields:
                        item1: "[[[ return variables.ulm_school_elementary + ':' ]]]"


                    # High School
                    - type: "custom:button-card"
                      template: 
                        - "popup_text_info"
                        - "direction_rtl"
                        - "popup_school_high_info"
                        - "ulm_language_variables"
                      custom_fields:
                        item1: "[[[ return variables.ulm_school_high + ':' ]]]"


                    # School Day sensor
                    - type: "custom:button-card"
                      template: 
                        - "popup_text_info"
                        - "direction_rtl"
                        - "popup_school_day_sensor_info"
                      custom_fields:
                        item1: "חיישן יום לימודים: "

                    # School Vacation sensor
                    - type: "custom:button-card"
                      template: 
                        - "popup_text_info"
                        - "direction_rtl"
                        - "popup_school_vacation_sensor_info"
                      custom_fields:
                        item1: "חיישן חופשות: "


                - type: "custom:button-card"
                  template: spacer
                  variables:
                    height: 20px
                    

                ############################################################################
                #                                                                          #
                #   Buttons                                                                #
                #                                                                          #
                ############################################################################

                - type: grid
                  square: false
                  columns: 1
                  cards:

                    - type: "custom:button-card"
                      template: 
                        #- "red_on"
                        - "deep_orange_background_on"
                        - "popup_button_ha_style"
                      entity: 'input_boolean.school_mode'
                      name: 'School Mode'
                      tap_action:
                        action: 'call-service'
                        service: 'input_boolean.toggle'
                        service_data:
                          entity_id: 'input_boolean.school_mode'


                - type: "custom:button-card"
                  template: spacer


            - type: custom:button-card
              template: card_blank


popup_school_elementary_info:
  custom_fields:
    item2: |-
      [[[ 
        if ( states['binary_sensor.elementary_vacation'].state == 'on' )
          return states['sensor.school_summary'].state;
        else
          return variables.ulm_school_regular; 
      ]]]

popup_school_high_info:
  custom_fields:
    item2: |-
      [[[ 
        if ( states['binary_sensor.high_vacation'].state == 'on' )
          return states['sensor.school_summary'].state;
        else
          return variables.ulm_school_regular; 
      ]]]

popup_school_day_sensor_info:
  custom_fields:
    item2: |-
      [[[ 
        if ( states['binary_sensor.school_day'].state == 'on' )
          return 'לימודים';
        else
          return 'לא';
      ]]]

popup_school_vacation_sensor_info:
  custom_fields:
    item2: |-
      [[[ 
        if ( states['binary_sensor.school_vacation'].state == 'on' )
          return 'חופש';
        else
          return 'לא';
      ]]]       