slate:

      # My Styles
      border-radius: 8px
      picture-elements-text-color: '#F0F0F0'                                          # Picture Element card text color
      picture-elements-icon-color: '#F0F0F0'                                          # Picture Element card icon color
      sensibo-cool-color: 'rgb(43, 154, 249)'                                         # Sensibo cool color
      sensibo-heat-color: 'rgb(255, 129, 0)'                                          # Sensibo heat color
      sensibo-fan-only-color: 'rgba(117,189,111,1)'                                   # Sensibo fan only color
      sensibo-auto-color: 'var(--picture-elements-icon-color)'                        # Sensibo auto color
      graph-border-radius: 'var(--border-radius)'                                     # Graph border radius

      # My Button Card Styles
      button-card-border-radius: 'var(--border-radius)'                               # Button Card corners radius
      button-card-background-color: 'var(--paper-card-background-color)'              # Button Card background color
      button-card-icon-color: 'var(--paper-item-icon-color)'                          # Button Card icon color
      button-card-text-color: 'var(--primary-text-color)'                             # Button Card text color
      button-card-corner-text-color: 'var(--secondary-text-color)'                    # Button card corner field text color
      button-card-cust-1-text-color: 'var(--secondary-text-color)'                    # Button Card cust_1 field text color
      button-card-cust-2-text-color: 'var(--secondary-text-color)'                    # Button Card cust_2 field text color
      button-card-disabled-text-color: 'var(--disabled-text-color)'                   # Button Card disabled text color
      button-card-input-select-background: 'var(--button-card-on-background)'         # Button Card selected item color
      button-card-on-background: 'var(--disabled-text-color)'                         # Button Card ON color
      button-color-green: 'rgba(117,189,111,1)'                                       # Button Card green background (ON mode)
      title-button-background: 'var(--paper-card-header-color)'                       # Title button background color
      title-button-text-color: 'var(--primary-text-color)'                            # Title button text color
      remote-button-background: 'var(--paper-card-background-color)'                  # Remote button background color
      remote-button-alt-background: 'var(--disabled-text-color)'                      # Remote button alternative background color
      remote-button-icon: 'var(--primary-text-color)'                                 # Remote button icon color
      remote-button-border-radius: 5px                                                # Remote button corners radius

      # My Colors
      lights-button-background: 'rgba(75,81,92,1.0)'
      label-button-background: 'rgb(97,103,114)'

      # Main colors
      primary-color: '#2980b9'
      accent-color: '#b58e31'
      dark-primary-color: '#2980b9'
      light-primary-color: '#2980b9'
      # Text colors
      primary-text-color: '#FFFFFF'
      text-primary-color: 'var(--primary-text-color)'
      secondary-text-color: '#b58e31'
      disabled-text-color: '#777777'
      label-badge-border-color: 'green'
      # Sidebar
      sidebar-icon-color: '#777777'
      # Background colors
      primary-background-color: '#222222'
      secondary-background-color: '#222222'
      divider-color: 'rgba(0, 0, 0, .12)'
      table-row-background-color: '#292929'
      table-row-alternative-background-color: '#292929'
      # Nav Menu
      paper-listbox-color: '#777777'
      paper-listbox-background-color: '#141414'
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#222222'
      # Paper card
      paper-card-header-color: '#2980b9'
      paper-card-background-color: '#292929'
      paper-dialog-background-color: '#292929'
      paper-item-icon-color: 'var(--primary-text-color)'
      paper-item-icon-active-color: '#b58e31'
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#292929'
      paper-tabs-selection-bar-color: 'green'
      # Labels
      label-badge-red: 'var(--primary-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      label-badge-background-color: '#222222'
      # Switches
      paper-toggle-button-checked-button-color: '#2980b9'
      paper-toggle-button-checked-bar-color: '#2980b9'
      paper-toggle-button-checked-ink-color: '#2980b9'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
      # Sliders
      paper-slider-knob-color: '#2980b9'
      paper-slider-knob-start-color: '#2980b9'
      paper-slider-pin-color: '#2980b9'
      paper-slider-active-color: '#2980b9'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      # Google colors
      google-red-500: '#b58e31'
      google-green-500: '#2980b9'
      #Changes to fix history/logbook menus
      lumo-primary-text-color: '#2980b9'
      lumo-secondary-text-color: '#2980b9'
      lumo-primary-color: '#2980b9'
      #Calendar day numbers
      lumo-body-text-color: '#b58e31'
      #Calendar/Date-Picker Background
      lumo-base-color: '#222222'
      #Month/Year header
      lumo-header-text-color: 'var(--lumo-body-text-color)'
      #DayOfWeek Header
      lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
      lumo-shade: '#222222'
      lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
      lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
      lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
      lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
      lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
      lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
      lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
      lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
      lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
      lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
      lumo-tint-5pct: '#222222'