Smart - Dark:
  ### Fonts ###
  primary-font-family: "'Open Sans','Rubik',Roboto,sans-serif"
  paper-font-common-base_-_font-family: "var(--primary-font-family)"
  paper-font-common-code_-_font-family: "var(--primary-font-family)"
  paper-font-body_-_font-family: "var(--primary-font-family)"
  paper-font-subhead_-_font-family: "var(--primary-font-family)"
  paper-font-headline_-_font-family: "var(--primary-font-family)"
  paper-font-caption_-_font-family: "var(--primary-font-family)"
  paper-font-title_-_font-family: "var(--primary-font-family)"

  ha-card-border-radius: "5px"

  ### Main Interface Colors ###
  primary-color: "#000000"
  light-primary-color: "#B5B5B5"
  primary-background-color: "#000000"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#2a2a2a"
  ### Text ###
  primary-text-color: "#ffffff"
  secondary-text-color: "#ffffff"
  text-primary-color: "#ffffff"
  disabled-text-color: "#a1a1a1"
  ### Sidebar Menu ###
  sidebar-background-color: "#000000"
  sidebar-icon-color: "#B5B5B5"
  sidebar-text-color: "#ffffff"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#4197FE"
  sidebar-selected-text-color: "#ffffff"
  ### States and Badges ###
  state-icon-color: "#B5B5B5"
  state-icon-active-color: "#ffb750"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#E59D37"
  paper-slider-knob-start-color: "#ffd89f"
  paper-slider-pin-color: "#ffd89f"
  paper-slider-active-color: "#ffd89f"
  paper-slider-secondary-color: var(--light-primary-color)
  paper-slider-container-color: "#4e4e4e"
  ### Labels ###
  label-badge-background-color: "#0057f5"
  label-badge-text-color: "#F1F1F1"
  label-badge-red: "#6C7B9B"
  ### Cards ###
  paper-card-background-color: "#2c2c2c"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#ffb750"
  paper-toggle-button-checked-bar-color: "#ffb750"
  paper-toggle-button-unchecked-button-color: "#6da3ff"
  paper-toggle-button-unchecked-bar-color: "#c1c1c1"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)

  iron-overlay-backdrop-background-color: "#B5B5B5"
  mdc-theme-primary: "#4197FE"