type: vertical-stack
cards:


############################################################################
#                                                                          #
#   Title                                                                  #
#                                                                          #
############################################################################

  - type: horizontal-stack
    cards:
    
      - type: custom:decluttering-card
        template: title_button_card
        variables:
          - name: Rooms

        
############################################################################
#                                                                          #
#   Rooms                                                                  #
#                                                                          #
############################################################################

  - type: horizontal-stack
    cards:

#       - type: custom:button-card
#         template: shoulder_blank_card

      - type: custom:decluttering-card
        template: menu_button
        variables:
          - entity: light.living_room
          - name: Living Room
          - icon: mdi:sofa
          #- icon: fas:couch
          - corner_2_field: "[[[
                  if (states['climate.living_room'].state == 'unavailable') 
                  return `<span></span>`;
                  else return `<span><span style='text-transform: capitalize'>${states['sensor.sensibo_living_room_temp'].state}째C</span></span>`;                               
                  ]]]"
          - corner_2_text_color: "[[[
                  if (states['sensor.sensibo_living_room_temp'].state >= 30) return '#bf4040';
                  if (states['sensor.sensibo_living_room_temp'].state >= 26 && states['sensor.sensibo_living_room_temp'].state < 30) return '#bf9540';
                  if (states['sensor.sensibo_living_room_temp'].state >= 18 && states['sensor.sensibo_living_room_temp'].state < 26) return 'rgba(117,189,111,1.0)';
                  if (states['sensor.sensibo_living_room_temp'].state < 18) return 'rgb(43, 154, 249)';
                  ]]]"
          - cust_1_field: "[[[
                  return `<ha-icon icon='mdi:television' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>${states['sensor.living_room_tv'].state}</span></span>`;
                  ]]]"
          - cust_1_icon_color: "[[[
                  if (states['sensor.living_room_tv'].state == 'Off') return 'var(--paper-item-icon-color)';
                  else return 'var(--paper-item-icon-active-color)';
                  ]]]"
          - cust_2_field: "[[[
                  if (states['climate.living_room'].state == 'unavailable')
                  return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>unavailable</span></span>`;                  
                  else if (states['climate.living_room'].state == 'off')
                  return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>off</span></span>`;
                  else return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>${states['climate.living_room'].state} ${states['climate.living_room'].attributes.temperature} ${states['climate.living_room'].attributes.fan_mode}</span></span>`
                  ]]]"
          - cust_2_icon_color: "[[[
                  if (states['climate.living_room'].state == 'unavailable') return 'var(--button-card-icon-color)';
                  if (states['climate.living_room'].state == 'off') return 'var(--button-card-icon-color)';
                  if (states['climate.living_room'].state == 'cool') return 'var(--sensibo-cool-color)';
                  if (states['climate.living_room'].state == 'heat') return 'var(--sensibo-heat-color)';
                  ]]]"
          - path: living_room                  

      - type: custom:decluttering-card
        template: menu_button
        variables:
          - entity: light.kitchen
          - name: Kitchen
          - icon: mdi:kettle
          #- icon: fas:utensils
          - cust_1_field: "[[[
                  if (states['switch.switcher_webapi'].state == 'off')
                  return `<ha-icon icon='mdi:shower' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>off</span></span>`;
                  else return `<ha-icon icon='mdi:shower' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>Auto off ${states['sensor.switcher_webapi_auto_off_time'].state}</span></span>`;
                  ]]]"
          - cust_1_icon_color: "[[[
                  if (states['switch.switcher_webapi'].state == 'off') return 'var(--paper-item-icon-color)';
                  else return 'var(--paper-item-icon-active-color)';
                  ]]]" 
          - path: kitchen

      - type: custom:decluttering-card
        template: menu_button
        variables:
          - entity: light.hallway
          - name: Hallway
          - icon: mdi:door-open
          #- icon: fas:door-open
          - path: hallway

  - type: horizontal-stack
    cards:

      - type: custom:decluttering-card
        template: menu_button
        variables:
          - entity: light.bedroom
          - name: Bedroom
          - icon: mdi:bed-empty
          #- icon: fas:bed
          - corner_2_field: "[[[
                  if (states['climate.bedroom'].state == 'unavailable') 
                  return `<span></span>`;
                  else return `<span><span style='text-transform: capitalize'>${states['sensor.sensibo_bedroom_temp'].state}째C</span></span>`;                               
                  ]]]"
          - corner_2_text_color: "[[[
                  if (states['sensor.sensibo_bedroom_temp'].state >= 30) return '#bf4040';
                  if (states['sensor.sensibo_bedroom_temp'].state >= 26 && states['sensor.sensibo_bedroom_temp'].state < 30) return '#bf9540';
                  if (states['sensor.sensibo_bedroom_temp'].state >= 18 && states['sensor.sensibo_bedroom_temp'].state < 26) return 'rgba(117,189,111,1.0)';
                  if (states['sensor.sensibo_bedroom_temp'].state < 18) return 'rgb(43, 154, 249)';
                  ]]]"
          - cust_1_field: "[[[
                  if (states['climate.bedroom'].state == 'unavailable')
                  return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>unavailable</span></span>`;                  
                  else if (states['climate.bedroom'].state == 'off')
                  return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>off</span></span>`;
                  else return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>${states['climate.bedroom'].state} ${states['climate.bedroom'].attributes.temperature} ${states['climate.bedroom'].attributes.fan_mode}</span></span>`
                  ]]]"
          - cust_1_icon_color: "[[[
                  if (states['climate.bedroom'].state == 'unavailable') return 'var(--button-card-icon-color)';
                  if (states['climate.bedroom'].state == 'off') return 'var(--button-card-icon-color)';
                  if (states['climate.bedroom'].state == 'cool') return 'var(--sensibo-cool-color)';
                  if (states['climate.bedroom'].state == 'heat') return 'var(--sensibo-heat-color)';
                  ]]]"
          - path: bedroom

      - type: custom:decluttering-card
        template: menu_button
        variables:
          - entity: light.work_room
          - name: Work Room
          - icon: mdi:desktop-classic
          #- icon: fas:computer-speaker
          - path: work_room
          - corner_2_field: "[[[
                  return `<span><span style='text-transform: capitalize'>${states['sensor.xiaomi_work_room_temperature'].state}째C</span></span>`;                               
                  ]]]"
          - corner_2_text_color: "[[[
                  if (states['sensor.xiaomi_work_room_temperature'].state >= 30) return '#bf4040';
                  if (states['sensor.xiaomi_work_room_temperature'].state >= 26 && states['sensor.xiaomi_work_room_temperature'].state < 30) return '#bf9540';
                  if (states['sensor.xiaomi_work_room_temperature'].state >= 18 && states['sensor.xiaomi_work_room_temperature'].state < 26) return 'rgba(117,189,111,1.0)';
                  if (states['sensor.xiaomi_work_room_temperature'].state < 18) return 'rgb(43, 154, 249)';
                  ]]]"
          - cust_1_field: "[[[
                  return `<ha-icon icon='mdi:desktop-tower' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span>dimka: <span>${states['binary_sensor.dimka_connected'].state}</span></span>`;
                  ]]]"
          - cust_1_icon_color: "[[[
                  if (states['binary_sensor.dimka_connected'].state == 'off') return 'var(--paper-item-icon-color)';
                  else return 'var(--paper-item-icon-active-color)';
                  ]]]"


      - type: custom:decluttering-card
        template: menu_button
        variables:
          - entity: light.kids_room
          - name: Kids Room
          - icon: mdi:face
          #- icon: fas:robot
          - corner_2_field: "[[[
                  if (states['climate.kids_room'].state == 'unavailable') 
                  return `<span></span>`;
                  else return `<span><span style='text-transform: capitalize'>${states['sensor.sensibo_kids_room_temp'].state}째C</span></span>`;                               
                  ]]]"
          - corner_2_text_color: "[[[
                  if (states['sensor.sensibo_kids_room_temp'].state >= 30) return '#bf4040';
                  if (states['sensor.sensibo_kids_room_temp'].state >= 26 && states['sensor.sensibo_kids_room_temp'].state < 30) return '#bf9540';
                  if (states['sensor.sensibo_kids_room_temp'].state >= 18 && states['sensor.sensibo_kids_room_temp'].state < 26) return 'rgba(117,189,111,1.0)';
                  if (states['sensor.sensibo_kids_room_temp'].state < 18) return 'rgb(43, 154, 249)';
                  ]]]"
          - cust_1_field: "[[[
                  if (states['climate.kids_room'].state == 'unavailable')
                  return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>unavailable</span></span>`;                  
                  else if (states['climate.kids_room'].state == 'off')
                  return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>off</span></span>`;
                  else return `<ha-icon icon='mdi:fan' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>${states['climate.kids_room'].state} ${states['climate.kids_room'].attributes.temperature} ${states['climate.kids_room'].attributes.fan_mode}</span></span>`
                  ]]]"
          - cust_1_icon_color: "[[[
                  if (states['climate.kids_room'].state == 'unavailable') return 'var(--button-card-icon-color)';
                  if (states['climate.kids_room'].state == 'off') return 'var(--button-card-icon-color)';
                  if (states['climate.kids_room'].state == 'cool') return 'var(--sensibo-cool-color)';
                  if (states['climate.kids_room'].state == 'heat') return 'var(--sensibo-heat-color)';
                  ]]]"
          - cust_2_field: "[[[
                  if (states['switch.kids_radiator'].state == 'off')
                  return `<ha-icon icon='mdi:radiator' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>off</span></span>`;               
                  else return `<ha-icon icon='mdi:radiator' style='width: 12px; height: 12px; color: var(--icon-color-sensor);'></ha-icon>
                  <span><span>${states['switch.kids_radiator'].state}</span> <span style='text-transform: capitalize'>${states['sensor.mqtt_kids_radiator_current'].state}A</span></span>`
                  ]]]"
          - cust_2_icon_color: "[[[
                  if (states['switch.kids_radiator'].state == 'unavailable') return 'var(--button-card-icon-color)';
                  if (states['switch.kids_radiator'].state == 'off') return 'var(--button-card-icon-color)';
                  if (states['switch.kids_radiator'].state == 'on') return 'var(--paper-item-icon-active-color)';
                  ]]]" 
          - path: kids_room


  - !include /config/lovelace/styles/separator_card.yaml