- platform: rest
  resource: !secret fully_device_info
  name: Fully Device Info
  json_attributes:
    - appVersionName
    - ssid
    - batteryLevel
    - wifiSignalLevel
    - ip4
    - androidVersion
    - deviceModel
    - currentPage
    - deviceName
    - mac
    - screenBrightness
    - plugged
    - lastAppStart
    - startUrl
    - isScreenOn
  value_template: 'OK'