card_switcher:
  variables:
    ulm_card_switcher_name: "Boiler"
    ulm_card_switcher_time_left: ""
    ulm_card_switcher_timer_minutes: ""
  triggers_update: "all"
  styles:
    grid:
      - grid-template-areas: "'item1' 'item2'"
      - grid-template-columns: "1fr"
      - grid-template-rows: "min-content  min-content"
      - row-gap: "12px"
    card:
      - border-radius: "var(--border-radius)"
      - box-shadow: "var(--box-shadow)"
      - padding: "12px"
  custom_fields:
    item1:
      card:
        triggers_update: "all"
        variables:
          ulm_card_switcher_time_left: '[[[ return variables.ulm_card_switcher_time_left ]]]'
          ulm_card_switcher_electric_current: '[[[ return variables.ulm_card_switcher_electric_current ]]]'
          ulm_card_switcher_entity: '[[[ return variables.ulm_card_switcher_entity ]]]'
          ulm_card_switcher_timer_minutes: '[[[ return variables.ulm_card_switcher_timer_minutes ]]]'
          ulm_card_switcher_timer_script: '[[[ return variables.ulm_card_switcher_timer_script ]]]'
          ulm_card_switcher_auto_off: '[[[ return variables.ulm_card_switcher_auto_off ]]]'
        type: "custom:button-card"
        template:
          - "icon_info"
          - "ulm_language_variables"
          - "switcher"
          - "popup_switcher"
        # tap_action:
        #   action: "more-info"
        entity: "[[[ return variables.ulm_card_switcher_entity ]]]"
        name: "[[[ return variables.ulm_card_switcher_name ]]]"
    item2:
      card:
        type: "custom:button-card"
        template: "list_3_items"
        custom_fields:
          item1:
            card:
              type: "custom:button-card"
              template: "widget_icon"
              tap_action:
                action: "call-service"
                service: "switch.toggle"
                service_data:
                  entity_id: "[[[ return variables.ulm_card_switcher_entity ]]]"
              icon: |
                [[[
                  if ( states[variables.ulm_card_switcher_entity].state == "on" )
                    return "mdi:power-cycle";
                  else 
                    return "mdi:power-off";
                ]]]
          item2:
            card:
              type: "custom:button-card"
              template: "widget_icon"
              tap_action:
                action: "call-service"
                service: "script.turn_on"
                service_data:
                  entity_id: "[[[ return variables.ulm_card_switcher_timer_script ]]]"
              icon: "mdi:av-timer"
          item3:
            card:
              type: "custom:button-card"
              template: "switcher_next_select"
              name: "[[[ return states[variables.ulm_card_switcher_timer_minutes].state ]]]"
              tap_action:
                action: "call-service"
                service: "input_select.select_next"
                service_data:
                  entity_id: "[[[ return variables.ulm_card_switcher_timer_minutes ]]]"


switcher:
  triggers_update: "all"
  tap_action:
    action: "more-info"
  icon: 'mdi:waves'
  label: >-
    [[[
        if ( entity.state == 'on' )
          return states[variables.ulm_card_switcher_time_left].state  
            + " â€¢ " + states[variables.ulm_card_switcher_electric_current].state + "A";
        else 
          return variables.ulm_off;
    ]]]
  state:
    - operator: "template"
      value: "[[[ return entity.state == 'on'; ]]]"
      styles:
        icon:
          - color: "rgba(var(--color-red),1)"
        img_cell:
          - background-color: "rgba(var(--color-red),0.2)"


switcher_next_select:
  show_icon: false
  show_name: true
  styles:
    grid:
      - grid-template-areas: "'n'"
    card:
      - box-shadow: "none"
      - padding: "0px"
      - background-color: "rgba(var(--color-theme),0.05)"
      - border-radius: "14px"
      - place-self: "center"
      - height: "42px"
    name:
      - color: "rgba(var(--color-theme),0.9)"
      - font-weight: '500'
  size: "20px"
  color: "var(--google-grey)"          