- alias: 'HA Startup'
  initial_state: 'true'
  trigger:
    - trigger: homeassistant
      event: start
  action:

    # DIMKA status update on Startup
    # - service: mqtt.publish 
    #   data:
    #     topic: "iotlink/home/dimka/refresh"
    #     payload: ""

    # Startup Notification
    #- service: notify.dimatelegram
    - service: notify.mobile_app_iphonedima
      data:
        title: 'System'
        message: 'Up and Running'

    # Sync Tasmota states on start-up
    # - service: mqtt.publish
    #   data:
    #     topic: "cmnd/tasmotas/state"
    #     payload: ""
    # - service: mqtt.publish
    #   data:
    #     topic: "cmnd/tasmotas/power0"
    #     payload: ""

    # Wake up Xiaomy Gateway light
    # - service: light.turn_off 
    #   data:
    #     entity_id: "light.xiaomi_gateway_servers"

    # Fully Load URL
    #- service: rest_command.fully_living_room_load_url
    # - service: button.press
    #   target:
    #     entity_id: button.fully_living_room_load_start_url 

    # Force Publish HA Birth Message
    # - service: mqtt.publish
    #   data:
    #     topic: "homeassistant/status"
    #     payload: "online"