script:

############################################################################
#                                                                          #
#   Update Home Assistant Container                                        #
#                                                                          #
############################################################################

  update_homeassistant_container:
    alias: "Update Home Assitant Container"
    sequence:
      #- service: shell_command.update_homeassistant_container
      - service: rest_command.update_homeassistant_container