# Light switches
switch.living_room_light:
    icon: mdi:lightbulb
switch.dining_light:
    icon: mdi:lightbulb
switch.kitchen_light:
    icon: mdi:lightbulb
switch.serv_balcony_light:
    icon: mdi:lightbulb
switch.balcony_light:
    icon: mdi:lightbulb
switch.enterence_light:
    icon: mdi:lightbulb
switch.hall_light:
    icon: mdi:lightbulb
switch.bedroom_light:
    icon: mdi:lightbulb
switch.kids_room_light:
    icon: mdi:lightbulb
switch.work_room_light:
    icon: mdi:lightbulb
    
# Lights
light.living_room:
    assumed_state: true
light.dining:
    assumed_state: true
light.kitchen:
    assumed_state: true
light.service_balcony:
    assumed_state: true
light.balcony:
    assumed_state: true
light.enterence:
    assumed_state: true
light.hall:
    assumed_state: true
light.bedroom:
    assumed_state: true
light.kids_room:
    assumed_state: true
light.work_room:
    assumed_state: true
    
# Yeelight
light.bedroom_ceiling:
    icon: mdi:ceiling-light
    
# Harmony
sensor.living_room:
    icon: mdi:remote
switch.baltic_tv:
    icon: mdi:television-classic
switch.shield_tv:
    icon: mdi:movie
switch.smart_tv:
    icon: mdi:television
script.reciever_volume_up:
    icon: mdi:volume-plus
script.reciever_volume_down:
    icon: mdi:volume-minus
script.reciever_volume_mute:
    icon: mdi:volume-mute
    
# iPhone sensors
sensor.iphonexsdima_battery_state:
    hidden: true
sensor.iphonexsdima_battery_level:
    hidden: true
sensor.iphonexsdima_battery_state_2:
    hidden: true
sensor.iphonexsdima_battery_level_2:
    hidden: true
    
# Router sensors
sensor.archer_vr600_bytes_received:
    hidden: true
sensor.archer_vr600_bytes_sent:
    hidden: true
sensor.archer_vr600_kbyte_sec_received:
    hidden: true
    friendly_name: Download
    icon: mdi:download
sensor.archer_vr600_kbyte_sec_sent:
    hidden: true
    friendly_name: Upload
    icon: mdi:upload
sensor.archer_vr600_packets_received:
    hidden: true
sensor.archer_vr600_packets_sec_received:
    hidden: true
sensor.archer_vr600_packets_sec_sent:
    hidden: true
sensor.archer_vr600_packets_sent:
    hidden: true
    
# Synology NAS
sensor.total_size_volume_1:
    friendly_name: Total Size
    icon: mdi:harddisk
sensor.used_space_volume_1:
    friendly_name: Used Space
sensor.volume_used_volume_1:
    friendly_name: Volume Used
sensor.temperature_sda:
    friendly_name: Disk 1 Temp
sensor.temperature_sdb:
    friendly_name: Disk 2 Temp
sensor.cpu_load_total:
    friendly_name: CPU Load
sensor.memory_usage_real:
    friendly_name: Memory Usage
sensor.network_up:
    friendly_name: Network Up
sensor.network_down:
    friendly_name: Network Down
    
# Automation
script.goodnight_script:
    hidden: true
    icon: mdi:hotel
script.Lights_off:
    hidden: true
    icon: mdi:flash-off

# Switcher
script.switcher_turn_on_timer_script:
    icon: mdi:timer
    
    