view_css: 'padding-top: 96px !important;'
header_css:
  '
  height: 70px !important;
  -webkit-box-shadow: var(--footer-shadow); 
  -moz-box-shadow: var(--footer-shadow); 
  box-shadow: var(--footer-shadow);
  '
all_tabs_css: '--mdc-icon-size: 28px;'
#header_text: '{{ viewTitle }}'
split_mode: false
compact_mode: true
footer_mode: true
indicator_top: true
voice_hide: true
chevrons: false
hide_help: true
hide_unused: true
hide_config: true
hidden_tab_redirect: false
reverse_tab_direction: false
reverse_button_direction: false
fit_tabs: true
menu_hide: true