group:

############################################################################
#                                                                          #
#   All Climate Entities                                                   #
#                                                                          #
############################################################################

  all_climate_entities:
    name: All Climate Entities
    entities:
      - climate.living_room
      - climate.bedroom
      - climate.kids_room
      - switch.kids_radiator



############################################################################
#                                                                          #
#   All Light Entities                                                     #
#                                                                          #
############################################################################

  all_light_entities:
    name: All Light Entities
    entities:
      - light.living_room
      - light.dining
      - light.kitchen
      - light.service_balcony
      - light.balcony
      - light.entrance
      - light.hallway
      - light.bedroom
      - light.kids_room
      - light.work_room
      - light.bedside_dima_bulb
      - light.bedside_galit_bulb
      - light.kitchen_strips
      - light.xiaomi_gateway_servers
      - light.makeup
      - light.new_year_tree



############################################################################
#                                                                          #
#   All Cover Entities                                                     #
#                                                                          #
############################################################################

  all_cover_entities:
    name: All Cover Entities
    entities:
      - sensor.dummy_shutter_open
      - sensor.dummy_shutter_closed



############################################################################
#                                                                          #
#   All Window Entities                                                    #
#                                                                          #
############################################################################

  all_window_entities:
    name: All Window Entities
    entities:
      - binary_sensor.dummy_window_open
      - binary_sensor.dummy_window_closed



############################################################################
#                                                                          #
#   All Device Entities                                                    #
#                                                                          #
############################################################################

  all_device_switch_entities:
    name: All Device Entities
    entities:
      #- sensor.washer
      #- sensor.dryer
      #- sensor.dishwasher
      - remote.living_room
      - switch.switcher_webapi



############################################################################
#                                                                          #
#   All Tablets Is Charging Entities                                       #
#                                                                          #
############################################################################

  all_tablets_is_charging_entities:
    name: All Tablets Is Charging Entities
    entities:
      - binary_sensor.ronen_tab_is_charging
      - binary_sensor.kfir_tab_is_charging
      - binary_sensor.ipadminidima_is_charging


############################################################################
#                                                                          #
#   All Tablets Batteries                                                  #
#                                                                          #
############################################################################

  all_tablets_battery_entities:
    name: All Tablets Battery Entities
    entities:
      - sensor.ronen_tab_battery_level
      - sensor.kfir_tab_battery_level
      - sensor.ipadminidima_battery_level



############################################################################
#                                                                          #
#   All Motion Sensors Entities                                            #
#                                                                          #
############################################################################

  all_motion_sensor_entities:
    name: All Motion Sensor Entities
    entities:
      - binary_sensor.motion_living_room
      - binary_sensor.motion_kitchen
      - binary_sensor.motion_kitchen_2
      #- group.kitchen_motion_sensors




############################################################################
#                                                                          #
#   All Batteries Sensor Entities                                          #
#                                                                          #
############################################################################

  all_batteries_sensor_entities:
    name: All Batteries Sensor Entities
    entities:
      - sensor.xiaomi_work_room_temp_battery
      - sensor.xiaomi_living_room_motion_battery
      - sensor.xiaomi_kitchen_motion_battery
      - sensor.xiaomi_button_bedside_dima_battery
      - sensor.xiaomi_button_bedside_galit_battery
      - sensor.xiaomi_button_makeup_battery
      - sensor.xiaomi_button_kitchen_strip_right_battery
      - sensor.xiaomi_button_kitchen_strip_left_battery



############################################################################
#                                                                          #
#   All Ink Sensor Entities                                                #
#                                                                          #
############################################################################

  all_ink_sensor_entities:
    name: All Ink Sensor Entities
    entities:
      - sensor.mfc_j650dw_black_ink_remaining
      - sensor.mfc_j650dw_cyan_ink_remaining
      - sensor.mfc_j650dw_magenta_ink_remaining
      - sensor.mfc_j650dw_yellow_ink_remaining



############################################################################
#                                                                          #
#   All Computers Entities                                                 #
#                                                                          #
############################################################################

  all_computer_switch_entities:
    name: All Computers Entities
    entities:
      - switch.dimka


############################################################################
#                                                                          #
#   All Media Entities                                                     #
#                                                                          #
############################################################################

  # all_media_entities:
  #   name: All Media Entities
  #   entities:
      

############################################################################
#                                                                          #
#   All Persons Entities                                                   #
#                                                                          #
############################################################################

  all_person_entities:
    name: All Persons Entities
    entities:
      - person.dmatik
      - person.galit
      - person.ronen
      - person.kfir



############################################################################
#                                                                          #
#   All Tasmota Versions                                                   #
#                                                                          #
############################################################################

  all_tasmota_versions:
    name: All Tasmota Versions
    entities:
      - sensor.kids_radiator_firmware_version
      - sensor.bedroom_radiator_firmware_version
      - sensor.makeup_firmware_version
      - sensor.bedside_dima_bulb_firmware_version
      - sensor.bedside_galit_bulb_firmware_version
      - sensor.entrance_firmware_version
      - sensor.living_room_firmware_version
      - sensor.bedroom_firmware_version
      - sensor.balcony_firmware_version
      - sensor.hallway_firmware_version
      - sensor.kids_room_firmware_version
      - sensor.kitchen_firmware_version
      - sensor.dining_firmware_version
      - sensor.work_room_firmware_version

############################################################################
#                                                                          #
#   All Notification Entities                                              #
#                                                                          #
############################################################################

  all_notification_entities:
    name: All Notification Versions
    entities:
      - binary_sensor.ha_update_available
      - sensor.number_of_tasmota_versions_old
      - sensor.hacs
      - binary_sensor.zeg_update_available
      - binary_sensor.blaze_update_available