type: vertical-stack
cards:


############################################################################
#                                                                          #
#   Title                                                                  #
#                                                                          #
############################################################################

  - type: horizontal-stack
    cards:
      
      - type: custom:decluttering-card
        template: title_button_card
        variables:
          - name: Favorite Accessories 


############################################################################
#                                                                          #
#   Accessories                                                            #
#                                                                          #
############################################################################

  - type: custom:layout-card
    layout_type: grid

    layout_options:
      grid-template-columns: 1fr 1fr 1fr 1fr 1fr
      grid-template-rows: auto
      grid-gap: 0px 4px
      mediaquery:
        "(max-width: 450px)":
          grid-template-columns: 1fr 1fr 1fr
  # - type: grid
  #   columns: 3
  #   square: false
    cards:

      # - type: custom:decluttering-card # Lights
      #   template: lights_view_button
      #   variables:
      #     - name: Lights

      # - type: custom:decluttering-card # Motion
      #   template: motion_view_button
      #   variables:
      #     - name: Motion


      # - type: custom:decluttering-card # Climate
      #   template: climate_view_button
      #   variables:
      #     - name: Climate
      
      - type: custom:decluttering-card # Living Room TV
        template: harmony_button
        variables:
          - entity: remote.living_room
          - title: Main TV
          - name: living_room

      - type: custom:decluttering-card # Switcher
        template: switcher_button
        variables:
          - entity: switch.switcher_webapi
          - name: Boiler
          - icon: mdi:water-boiler
          - svg_path: 'M8 2C6.89 2 6 2.89 6 4V16C6 17.11 6.89 18 8 18H9V20H6V22H9C10.11 22 11 21.11 11 20V18H13V20C13 21.11 13.89 22 15 22H18V20H15V18H16C17.11 18 18 17.11 18 16V4C18 2.89 17.11 2 16 2H8M12 4.97A2 2 0 0 1 14 6.97A2 2 0 0 1 12 8.97A2 2 0 0 1 10 6.97A2 2 0 0 1 12 4.97M10 14.5H14V16H10V14.5Z'
          - svg_path_on: 'M 8,2 C 6.89,2 6,2.89 6,4 v 12 c 0,1.11 0.89,2 2,2 h 1 c 2,0 0,0 2,0 h 2 c 2,0 0,0 2,0 h 1 c 1.11,0 2,-0.89 2,-2 V 4 C 18,2.89 17.11,2 16,2 H 8 m 4,2.97 c 1.104569,0 2,0.8954305 2,2 0,1.1045695 -0.895431,2 -2,2 -1.104569,0 -2,-0.8954305 -2,-2 0,-1.1045695 0.895431,-2 2,-2 m -2,9.53 h 4 V 16 h -4 z'

      - type: custom:decluttering-card # Kids Room Radiator
        template: socket_button
        variables:
          - entity: switch.kids_radiator
          - name: Kids Radiator
          - icon: mdi:radiator
          - sensor_power: sensor.mqtt_kids_radiator_power
          - svg_path: 'M7.95,3L6.53,5.19L7.95,7.4H7.94L5.95,10.5L4.22,9.6L5.64,7.39L4.22,5.19L6.22,2.09L7.95,3M13.95,2.89L12.53,5.1L13.95,7.3L13.94,7.31L11.95,10.4L10.22,9.5L11.64,7.3L10.22,5.1L12.22,2L13.95,2.89M20,2.89L18.56,5.1L20,7.3V7.31L18,10.4L16.25,9.5L17.67,7.3L16.25,5.1L18.25,2L20,2.89M2,22V14A2,2 0 0,1 4,12H20A2,2 0 0,1 22,14V22H20V20H4V22H2M6,14A1,1 0 0,0 5,15V17A1,1 0 0,0 6,18A1,1 0 0,0 7,17V15A1,1 0 0,0 6,14M10,14A1,1 0 0,0 9,15V17A1,1 0 0,0 10,18A1,1 0 0,0 11,17V15A1,1 0 0,0 10,14M14,14A1,1 0 0,0 13,15V17A1,1 0 0,0 14,18A1,1 0 0,0 15,17V15A1,1 0 0,0 14,14M18,14A1,1 0 0,0 17,15V17A1,1 0 0,0 18,18A1,1 0 0,0 19,17V15A1,1 0 0,0 18,14Z'
          - svg_path_on: 'm 2,22 v -8 c 0,-1.104569 0.8954305,-2 2,-2 h 16 c 1.104569,0 2,0.895431 2,2 v 8 H 20 V 20 H 4 v 2 H 2 m 4,-8 c -0.5522847,0 -1,0.447715 -1,1 v 2 c 0,0.552285 0.4477153,1 1,1 0.5522847,0 1,-0.447715 1,-1 V 15 C 7,14.447715 6.5522847,14 6,14 m 4,0 c -0.5522847,0 -1,0.447715 -1,1 v 2 c 0,0.552285 0.4477153,1 1,1 0.552285,0 1,-0.447715 1,-1 v -2 c 0,-0.552285 -0.447715,-1 -1,-1 m 4,0 c -0.552285,0 -1,0.447715 -1,1 v 2 c 0,0.552285 0.447715,1 1,1 0.552285,0 1,-0.447715 1,-1 v -2 c 0,-0.552285 -0.447715,-1 -1,-1 m 4,0 c -0.552285,0 -1,0.447715 -1,1 v 2 c 0,0.552285 0.447715,1 1,1 0.552285,0 1,-0.447715 1,-1 v -2 c 0,-0.552285 -0.447715,-1 -1,-1 z'

      - type: custom:decluttering-card # Living Room Light
        template: light_button
        variables:
          - entity: light.living_room
          - name: Living Room

      - type: custom:decluttering-card # Dining Light
        template: light_button
        variables:
          - entity: light.dining
          - name: Dining

      - type: custom:decluttering-card # Kitchen Light
        template: light_button
        variables:
          - entity: light.kitchen
          - name: Kitchen

      - type: custom:decluttering-card # Bedroom Light
        template: light_button
        variables:
          - entity: light.bedroom
          - name: Bedroom

      - type: custom:decluttering-card # Bedside Galit Light
        template: color_light_button
        variables:
          - entity: light.bedside_galit
          - name: Galit
          - icon: mdi:lamp
          - svg_path: 'M8,2H16L20,14H4L8,2M11,15H13V20H18V22H6V20H11V15Z'
          - svg_path_on: 'm 8,2 h 8 l 4,12 H 4 L 8,2'

      - type: custom:decluttering-card # Bedside Dima Light
        template: color_light_button
        variables:
          - entity: light.bedside_dima
          - name: Dima
          - icon: mdi:lamp
          - svg_path: 'M8,2H16L20,14H4L8,2M11,15H13V20H18V22H6V20H11V15Z'
          - svg_path_on: 'm 8,2 h 8 l 4,12 H 4 L 8,2'

      - type: custom:decluttering-card # Hallway Light
        template: light_button
        variables:
          - entity: light.hallway
          - name: Hallway

      - type: custom:decluttering-card # Parking Gate Kineret 74
        template: garage_door_button
        variables:
          - entity: script.open_parking_gate_74
          - name: Front Gate

      - type: custom:decluttering-card # Parking Gate Kineret 72
        template: garage_door_button
        variables:
          - entity: script.open_parking_gate_72
          - name: Back Gate

      - type: custom:decluttering-card # Dimka PC
        template: pc_button
        variables:
          - entity: switch.dimka
          - name: Dimka PC
          - icon: mdi:desktop-classic
          - svg_path: 'M6,2C4.89,2 4,2.89 4,4V12C4,13.11 4.89,14 6,14H18C19.11,14 20,13.11 20,12V4C20,2.89 19.11,2 18,2H6M6,4H18V12H6V4M4,15C2.89,15 2,15.89 2,17V20C2,21.11 2.89,22 4,22H20C21.11,22 22,21.11 22,20V17C22,15.89 21.11,15 20,15H4M8,17H20V20H8V17M9,17.75V19.25H13V17.75H9M15,17.75V19.25H19V17.75H15Z'
          - svg_path_on: 'M 6,2 C 4.89,2 4,2.89 4,4 v 8 c 0,1.11 0.89,2 2,2 h 12 c 1.11,0 2,-0.89 2,-2 V 4 C 20,2.89 19.11,2 18,2 H 6 m 0,2 h 12 v 8 H 6 V 4 M 4,15 c -1.11,0 -2,0.89 -2,2 v 3 c 0,1.11 0.89,2 2,2 h 16 c 1.11,0 2,-0.89 2,-2 v -3 c 0,-1.11 -0.89,-2 -2,-2 H 4 m 4,2 h 12 v 3 H 8 v -3'

    

      # - type: custom:decluttering-card # Red Alert
      #   template: redalert_button
      #   variables:
      #     - entity: binary_sensor.redalert_all
      #     - name: Red Alert

      # - type: custom:decluttering-card # Hovid
      #   template: menu_new_button
      #   variables:
      #     - entity: ""
      #     - name: Health
      #     - icon: mdi:pill
      #     - cust_1_field: "Overview"
      #     - path: health

      # - type: custom:decluttering-card # Health
      #   template: health_view_button
      #   variables:
      #     - name: Health

      # - type: custom:decluttering-card # Crypto
      #   template: crypto_view_button

  - !include /config/lovelace/styles/separator_card.yaml
