default:
  - tap_action:
      action: more-info
  - hold_action:
      action: none
card:
  type: picture-elements
  style: |
    ha-card {
      border-radius: var(--border-radius);
      #border: var(--border);
      #box-shadow: var(--box-shadow);
      overflow: hidden;
    }
  image: '[[image]]'
  elements:
    - type: image
      entity: device_tracker.[[name]]
      image: '[[image]]'
      tap_action: '[[tap_action]]'
      hold_action: '[[hold_action]]'
      style:
        left: 50%
        top: 50%
        width: 100%
        heigth: 100%
    - type: state-label
      entity: device_tracker.[[name]]
      style:
        left: 0
        bottom: 0
        pointer-events: none
        font-size: 16px
        line-height: 24px
        color: white
        background-color: rgba(0, 0, 0, 0.3)
        width: 100%
        transform: initial
        padding: 0 8px
    - type: state-label
      entity: '[[battery]]'
      style:
        top: 0
        '[[direction]]': 0
        pointer-events: none
        transform: initial
        font-size: 16px
        color: "#FFFFFF"
        line-height: 32px
        padding: 1px 30px
    - type: icon
      icon: mdi:cellphone-iphone
      style:
        top: 0
        '[[direction]]': 0
        pointer-events: none
        transform: scale(0.8)
        color: "#FFFFFF"
        line-height: 32px
        padding: 8px 10px  