title: מדיה
path: tiles_media
visible: false
type: sections
subview: true
max_columns: 3

badges:

  # Media Chip
  - type: 'custom:button-card'
    template:
      - 'chip_two_rows_media'
    variables:
      ulm_chip_icon_state_entity: sensor.media_devices_on_counter


sections:

  ############################################################################
  #                                                                          #
  #   Living Room                                                            #
  #                                                                          #
  ############################################################################

  - type: grid
    title: סלון  
    cards:

      # Living Room TV
      - type: tile
        entity: media_player.lg_webos_tv_oled77cs6la
        icon_tap_action:
          action: more-info

      # Apple TV Living Room
      - type: tile
        entity: media_player.apple_tv_living_room
        icon_tap_action:
          action: more-info



  ############################################################################
  #                                                                          #
  #   Basement                                                               #
  #                                                                          #
  ############################################################################

  - type: grid
    title: מרתף  
    cards:

      # Basement TV
      - type: tile
        entity: media_player.samsung_8_series_65
        icon_tap_action:
          action: more-info

      # Apple TV Basement
      - type: tile
        entity: media_player.apple_tv_basement
        icon_tap_action:
          action: more-info

      # Groot PC
      - type: 'custom:button-card'
        template: card_pc
        entity: switch.groot_hass_agent
        variables:
          #x_ulm_card_pc_name: "[[[ return variables.ulm_groot_pc; ]]]"
          ulm_card_pc_memoryusage: 'sensor.groot_memoryusage'
          ulm_card_pc_cpuload: 'sensor.groot_cpuload'
          ulm_card_pc_storage_1: 'sensor.groot_disk_c_used_space'
          ulm_card_pc_storage_2: 'sensor.groot_disk_d_used_space'
          ulm_card_pc_wake: 'script.groot_wake'
          ulm_card_pc_sleep: 'script.groot_sleep'
          ulm_card_pc_restart: 'script.groot_restart'
          ulm_card_pc_shutdown: 'script.groot_shutdown'
        layout_options:
          grid_columns: 2
          grid_rows: 1            



  ############################################################################
  #                                                                          #
  #   Work Room                                                              #
  #                                                                          #
  ############################################################################

  - type: grid
    title: חדר עבודה  
    cards:

      # Dimka PC
      - type: 'custom:button-card'
        template: card_pc
        entity: switch.dimka_hass_agent
        variables:
          #x_ulm_card_pc_name: "[[[ return variables.ulm_dimka_pc; ]]]"
          ulm_card_pc_memoryusage: 'sensor.dimka_memoryusage'
          ulm_card_pc_cpuload: 'sensor.dimka_cpuload'
          ulm_card_pc_storage_1: 'sensor.dimka_disk_c_used_space'
          ulm_card_pc_storage_2: 'sensor.dimka_disk_d_used_space'
          ulm_card_pc_wake: 'script.dimka_wake'
          ulm_card_pc_sleep: 'script.dimka_sleep'
          ulm_card_pc_restart: 'script.dimka_restart'
          ulm_card_pc_shutdown: 'script.dimka_shutdown'
        layout_options:
          grid_columns: 2
          grid_rows: 1    

