#
# iOS Dark Mode Theme
#
ios-dark-mode:

# Background image
      #background-image: 'center / cover no-repeat url("/local/images/backgrounds/dark_green_ios.jpg") fixed'
      background-image: 'center / cover no-repeat url("/local/images/backgrounds/light_blue_ios.jpg") fixed'
      #background-image: 'center / cover no-repeat url("/local/images/backgrounds/red_ios.jpg") fixed'
      #background-image: 'center / cover no-repeat url("/local/images/backgrounds/dark_blue_ios.jpg") fixed'
      #background-image: 'center / cover no-repeat url("/local/images/backgrounds/light_green_ios.jpg") fixed'

# My Styles
      border-radius: 10px
      picture-elements-text-color: '#F0F0F0'                                          # Picture Element card text color
      picture-elements-icon-color: '#F0F0F0'                                          # Picture Element card icon color
      sensibo-cool-color: 'rgba(43, 154, 249, 0.7)'                                   # Sensibo cool color
      sensibo-heat-color: 'rgba(255, 129, 0, 0.7)'                                    # Sensibo heat color
      sensibo-fan-only-color: 'rgba(117,189,111,0.7)'                                 # Sensibo fan only color
      sensibo-auto-color: 'var(--picture-elements-icon-color)'                        # Sensibo auto color
      graph-border-radius: 'var(--border-radius)'                                     # Graph border radius
      ch-background: 'var(--ha-card-background)' #'rgba(37, 129, 171, 0.7)'
      ch-active-tab-color: 'var(--primary-color)'
      ch-tab-indicator-color: 'rgba(240, 240, 240, 0)'

# My Button Card Styles
      button-card-border-radius: 'var(--border-radius)'                               # Button Card border radius
      button-card-background-color: 'var(--paper-card-background-color)'              # Button Card background color
      button-card-icon-color: 'var(--paper-item-icon-color)'                          # Button Card icon color
      button-card-text-color: 'var(--primary-text-color)'                             # Button Card text color
      button-card-corner-text-color: 'var(--secondary-text-color)'                    # Button card corner field text color
      button-card-cust-1-text-color: 'var(--secondary-text-color)'                    # Button Card cust_1 field text color
      button-card-cust-2-text-color: 'var(--secondary-text-color)'                    # Button Card cust_2 field text color
      button-card-disabled-text-color: 'var(--disabled-text-color)'                   # Button Card disabled text color
      button-card-input-select-background: 'var(--button-card-on-background)'         # Button Card selected item color
      button-card-on-background: 'var(--secondary-background-color)'                  # Button Card ON color
      button-color-green: 'rgba(48,210,87,0.7)' #'rgba(117,189,111,0.7)'              # Button Card green background (ON mode)
      title-border-radius: 5px                                                        # Title border radius
      title-button-background: 'rgba(37, 129, 171, 0.7)'                              # Title button background color
      title-button-text-color: 'var(--primary-text-color)'                            # Title button text color
      remote-button-background: 'var(--paper-card-background-color)'                  # Remote button background color
      remote-button-alt-background: 'var(--disabled-text-color)'                      # Remote button alternative background color
      remote-button-icon: 'var(--primary-text-color)'                                 # Remote button icon color
      remote-button-border-radius: 5px                                                # Remote button border radius
      button-card-lock-color: 'var(--secondary-text-color)'                           # Button Card lock color  
  
      # Global
      primary-color: '#2581ab' #'#0C64BB' #rgba(255, 159, 9, 1)  # from Apple systemOrange dark mode
      light-primary-color: "#B6B6C1"  # light gray (icons on left menu)
      primary-background-color: "#2c2c2e"  # systemGray5 dark mode
      secondary-background-color: rgba(25, 25, 25, 0.7)
      divider-color: 'rgba(0, 0, 0, .12)' #"#98989d"  # from Apple systemGray dark mode
      accent-color: '#2581ab' #'#0C64BB' #rgba(255, 159, 9, 1)
      # Text
      primary-text-color: "#FFF"
      secondary-text-color: "#d3d3d3"
      text-primary-color: "#FFF"
      disabled-text-color: "#232323"  # XXX: https://github.com/basnijholt/lovelace-ios-dark-mode-theme/issues/2
      text-dark-color: "#FFF"
      # Sidebar Menu
      sidebar-icon-color: var(--light-primary-color)
      sidebar-text-color: "#F1F1F1"
      sidebar-selected-background-color: var(--primary-background-color)
      sidebar-selected-icon-color: "#FFF"
      sidebar-selected-text-color: var(--sidebar-selected-icon-color)
      # States and Badges
      state-icon-color: '#F0F0F0' #"#FFF"
      state-icon-active-color: '#ffc107' #"#FFF"  # or make light icons yellow when active: rgba(255, 214, 10, 1)
      state-icon-unavailable-color: var(--disabled-text-color)
      # Sliders
      paper-slider-knob-color: "#FFF"
      paper-slider-knob-start-color: var(--paper-slider-knob-color)
      paper-slider-pin-color: var(--paper-slider-knob-color)
      paper-slider-active-color: "#0984ff"  # from Apple systemBlue dark mode
      paper-slider-secondary-color: var(--paper-slider-knob-color)
      paper-slider-container-color: rgba(255, 255, 255, 0.5)
      paper-slider-font-color: "#000"
      ha-slider-background: none !important
      # Labels
      label-badge-background-color: "#23232E"
      label-badge-text-color: "#F1F1F1"
      label-badge-red: rgba(255, 159, 9, 0.7)  # from Apple systemOrange dark mode
      # Cards
      card-background-color: var(--secondary-background-color)  # Unused entities table background
      paper-listbox-background-color: var(--primary-background-color)
      ha-card-border-radius: 10px
      ha-card-background: rgba(10, 10, 10, 0.4)
      paper-card-background-color: var(--ha-card-background)
      # Toggles
      paper-toggle-button-checked-button-color: "#484848"
      paper-toggle-button-checked-bar-color: "#484848"
      paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color)
      paper-toggle-button-unchecked-bar-color: var(--disabled-text-color)
      # Table row
      table-row-background-color: var(--primary-background-color)
      table-row-alternative-background-color: var(--secondary-background-color)
      # Switches
      switch-checked-color: "#30d257"  # XXX: remove when https://github.com/home-assistant/home-assistant-polymer/pull/4203 is in HA
      switch-checked-track-color: "#30d158"  # from Apple systemGreen dark mode
      switch-checked-button-color: "#FFF"
      # Other
      paper-dialog-background-color: rgba(55, 55, 55, 0.6)
      paper-item-icon-color: '#F0F0F0' #white  # also should mini-media-player icon white (but doesn't work by itself)
      paper-item-icon-active-color: '#ffc107'
      more-info-header-background: rgba(25, 25, 25, 0.5)
      # Custom
      mcg-title-letter-spacing: .15em
      mini-media-player-base-color: white
      mini-media-player-icon-color: white
      # mini-media-player-artwork-opacity: 0.7  # causing some bug